### ISSUE TITLE
Add support for retrieving vertical datum info

### ISSUE THREAD

**Issue by adamkorynta** [USACE/cwms-data-api#101]
The time series retrieval client API returns a TimeSeries object that contains the vertical datum information for the location with the ability to convert the time series values between datums.

**Comment by rripken** [comment]
#108 Should have added the vertical datum info for Elev Ts.

**Comment by adamkorynta** [comment]
I updated to the latest and am now getting this exception for a location that definitely exists (verified with /cwms-data/locations/ALTU endpoint)

Example cURL:

```
curl -X 'GET' \
  'http://localhost:11524/cwms-data/timeseries?name=ARBU.Elev.Inst.1Hour.0.Ccp-Rev&unit=SI&begin=2017-06-10T13%3A00%3A00Z&end=2017-11-10T13%3A00%3A00Z' \
  -H 'accept: application/json;version=2'
```

Server side stack:
```
Nov 19, 2021 2:13:09 PM cwms.radar.api.TimeSeriesController getAll
WARNING: -2082322036544541854: Not found.
cwms.radar.api.NotFoundException: java.sql.SQLException: ORA-20025: LOCATION_ID_NOT_FOUND: The Location: "ALTU" does not exist.
ORA-06512: at "CWMS_20.CWMS_ERR", line 59
ORA-06512: at "CWMS_20.CWMS_LOC", line 128
ORA-01403: no data found
ORA-06512: at "CWMS_20.CWMS_LOC", line 115
ORA-01403: no data found
ORA-06512: at "CWMS_20.CWMS_LOC", line 91
ORA-06512: at "CWMS_20.CWMS_TS", line 9873
ORA-01403: no data found
ORA-06512: at "CWMS_20.CWMS_TS", line 9855
ORA-06512: at "CWMS_20.CWMS_TS", line 131
ORA-01403: no data found
ORA-06512: at "CWMS_20.CWMS_TS", line 120
ORA-06512: at "CWMS_20.CWMS_TS", line 41
ORA-06512: at "CWMS_20.CWMS_TS", line 26
ORA-06512: at "CWMS_20.CWMS_TS", line 9923

	at cwms.radar.data.dao.TimeSeriesDaoImpl.getTimeseries(TimeSeriesDaoImpl.java:258)
	at cwms.radar.data.dao.TimeSeriesDaoImpl.getTimeseries(TimeSeriesDaoImpl.java:115)
	at cwms.radar.api.TimeSeriesController.getAll(TimeSeriesController.java:245)
	at io.javalin.apibuilder.CrudFunction$1.invoke$lambda-0(CrudHandler.kt:30)
	at io.javalin.apibuilder.CrudFunctionHandler.handle(CrudHandler.kt)
	at io.javalin.core.security.SecurityUtil.noopAccessManager(SecurityUtil.kt:20)
	at io.javalin.http.JavalinServlet.addHandler$lambda-5(JavalinServlet.kt:113)
	at io.javalin.http.JavalinServlet$service$tryBeforeAndEndpointHandlers$1.invoke(JavalinServlet.kt:44)
	at io.javalin.http.JavalinServlet$service$tryBeforeAndEndpointHandlers$1.invoke(JavalinServlet.kt:39)
	at io.javalin.http.JavalinServlet.service$tryWithExceptionMapper(JavalinServlet.kt:129)
	at io.javalin.http.JavalinServlet.service$tryBeforeAndEndpointHandlers(JavalinServlet.kt:39)
	at io.javalin.http.JavalinServlet.service(JavalinServlet.kt:87)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at cwms.radar.ApiServlet.service(ApiServlet.java:205)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:895)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1722)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: ORA-20025: LOCATION_ID_NOT_FOUND: The Location: "ALTU" does not exist.
ORA-06512: at "CWMS_20.CWMS_ERR", line 59
ORA-06512: at "CWMS_20.CWMS_LOC", line 128
ORA-01403: no data found
ORA-06512: at "CWMS_20.CWMS_LOC", line 115
ORA-01403: no data found
ORA-06512: at "CWMS_20.CWMS_LOC", line 91
ORA-06512: at "CWMS_20.CWMS_TS", line 9873
ORA-01403: no data found
ORA-06512: at "CWMS_20.CWMS_TS", line 9855
ORA-06512: at "CWMS_20.CWMS_TS", line 131
ORA-01403: no data found
ORA-06512: at "CWMS_20.CWMS_TS", line 120
ORA-06512: at "CWMS_20.CWMS_TS", line 41
ORA-06512: at "CWMS_20.CWMS_TS", line 26
ORA-06512: at "CWMS_20.CWMS_TS", line 9923

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:509)
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:461)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1104)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:550)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:268)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:655)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:270)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:91)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:807)
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:983)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1168)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3666)
	at oracle.jdbc.driver.T4CPreparedStatement.executeInternal(T4CPreparedStatement.java:1426)
	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3778)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1081)
	at sun.reflect.GeneratedMethodAccessor32.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:118)
	at com.sun.proxy.$Proxy9.execute(Unknown Source)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:209)
	at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:3416)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:268)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:350)
	at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:393)
	at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:380)
	at org.jooq.impl.AbstractResultQuery.fetchOne(AbstractResultQuery.java:545)
	at org.jooq.impl.AbstractResultQuery.fetchOne(AbstractResultQuery.java:550)
	at org.jooq.impl.SelectImpl.fetchOne(SelectImpl.java:2884)
	at cwms.radar.data.dao.TimeSeriesDaoImpl.getTimeseries(TimeSeriesDaoImpl.java:214)
	... 32 more
Caused by: Error : 20025, Position : 7, Sql = select "CWMS_20"."CWMS_TS"."GET_TS_ID"(:1 , "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"())) "NAME", "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"()) "OFFICE_ID", "CWMS_20"."CWMS_UTIL"."GET_DEFAULT_UNITS"("CWMS_20"."CWMS_TS"."GET_BASE_PARAMETER_ID"("CWMS_20"."CWMS_TS"."GET_TS_CODE"("CWMS_20"."CWMS_TS"."GET_TS_ID"(:2 , "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"())), "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"()))), :3 ) "UNITS", "CWMS_20"."CWMS_TS"."GET_INTERVAL"("CWMS_20"."CWMS_TS"."GET_TS_ID"(:4 , "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"()))) "INTERVAL", "CWMS_20"."CWMS_UTIL"."SPLIT_TEXT"("CWMS_20"."CWMS_TS"."GET_TS_ID"(:5 , "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"())), :6 , :7 , :8 ) "LOC_PART", upper("CWMS_20"."CWMS_UTIL"."SPLIT_TEXT"("CWMS_20"."CWMS_TS"."GET_TS_ID"(:9 , "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"())), :10 , :11 , :12 )) "PARM_PART", case upper("CWMS_20"."CWMS_UTIL"."SPLIT_TEXT"("CWMS_20"."CWMS_TS"."GET_TS_ID"(:13 , "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"())), :14 , :15 , :16 )) when :17  then "CWMS_20"."CWMS_LOC"."GET_VERTICAL_DATUM_INFO_F"("CWMS_20"."CWMS_UTIL"."SPLIT_TEXT"("CWMS_20"."CWMS_TS"."GET_TS_ID"(:18 , "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"())), :19 , :20 , :21 ), "CWMS_20"."CWMS_UTIL"."GET_DEFAULT_UNITS"("CWMS_20"."CWMS_TS"."GET_BASE_PARAMETER_ID"("CWMS_20"."CWMS_TS"."GET_TS_CODE"("CWMS_20"."CWMS_TS"."GET_TS_ID"(:22 , "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"())), "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"()))), :23 ), "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"())) else :24  end "VERTICAL_DATUM", (select count(*) from table("CWMS_20"."CWMS_TS"."RETRIEVE_TS_OUT_TAB"(
  "CWMS_20"."CWMS_TS"."GET_TS_ID"(
    'ALTU.Elev.Inst.1Hour.0.Ccp-Rev', 
    "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"())
  ), 
  "CWMS_20"."CWMS_UTIL"."GET_DEFAULT_UNITS"(
    "CWMS_20"."CWMS_TS"."GET_BASE_PARAMETER_ID"("CWMS_20"."CWMS_TS"."GET_TS_CODE"(
      "CWMS_20"."CWMS_TS"."GET_TS_ID"(
        'ALTU.Elev.Inst.1Hour.0.Ccp-Rev', 
        "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"())
      ), 
      "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"())
    )), 
    'SI'
  ), 
  "CWMS_20"."CWMS_UTIL"."TO_TIMESTAMP"(1497099600000), 
  "CWMS_20"."CWMS_UTIL"."TO_TIMESTAMP"(1510318800000), 
  'UTC', 
  null, 
  null, 
  null, 
  null, 
  null, 
  null, 
  null, 
  "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"())
))) "TOTAL" from dual, OriginalSql = select "CWMS_20"."CWMS_TS"."GET_TS_ID"(?, "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"())) "NAME", "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"()) "OFFICE_ID", "CWMS_20"."CWMS_UTIL"."GET_DEFAULT_UNITS"("CWMS_20"."CWMS_TS"."GET_BASE_PARAMETER_ID"("CWMS_20"."CWMS_TS"."GET_TS_CODE"("CWMS_20"."CWMS_TS"."GET_TS_ID"(?, "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"())), "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"()))), ?) "UNITS", "CWMS_20"."CWMS_TS"."GET_INTERVAL"("CWMS_20"."CWMS_TS"."GET_TS_ID"(?, "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"()))) "INTERVAL", "CWMS_20"."CWMS_UTIL"."SPLIT_TEXT"("CWMS_20"."CWMS_TS"."GET_TS_ID"(?, "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"())), ?, ?, ?) "LOC_PART", upper("CWMS_20"."CWMS_UTIL"."SPLIT_TEXT"("CWMS_20"."CWMS_TS"."GET_TS_ID"(?, "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"())), ?, ?, ?)) "PARM_PART", case upper("CWMS_20"."CWMS_UTIL"."SPLIT_TEXT"("CWMS_20"."CWMS_TS"."GET_TS_ID"(?, "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"())), ?, ?, ?)) when ? then "CWMS_20"."CWMS_LOC"."GET_VERTICAL_DATUM_INFO_F"("CWMS_20"."CWMS_UTIL"."SPLIT_TEXT"("CWMS_20"."CWMS_TS"."GET_TS_ID"(?, "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"())), ?, ?, ?), "CWMS_20"."CWMS_UTIL"."GET_DEFAULT_UNITS"("CWMS_20"."CWMS_TS"."GET_BASE_PARAMETER_ID"("CWMS_20"."CWMS_TS"."GET_TS_CODE"("CWMS_20"."CWMS_TS"."GET_TS_ID"(?, "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"())), "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"()))), ?), "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"())) else ? end "VERTICAL_DATUM", (select count(*) from table("CWMS_20"."CWMS_TS"."RETRIEVE_TS_OUT_TAB"(
  "CWMS_20"."CWMS_TS"."GET_TS_ID"(
    'ALTU.Elev.Inst.1Hour.0.Ccp-Rev', 
    "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"())
  ), 
  "CWMS_20"."CWMS_UTIL"."GET_DEFAULT_UNITS"(
    "CWMS_20"."CWMS_TS"."GET_BASE_PARAMETER_ID"("CWMS_20"."CWMS_TS"."GET_TS_CODE"(
      "CWMS_20"."CWMS_TS"."GET_TS_ID"(
        'ALTU.Elev.Inst.1Hour.0.Ccp-Rev', 
        "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"())
      ), 
      "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"())
    )), 
    'SI'
  ), 
  "CWMS_20"."CWMS_UTIL"."TO_TIMESTAMP"(1497099600000), 
  "CWMS_20"."CWMS_UTIL"."TO_TIMESTAMP"(1510318800000), 
  'UTC', 
  null, 
  null, 
  null, 
  null, 
  null, 
  null, 
  null, 
  "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"())
))) "TOTAL" from dual, Error Msg = ORA-20025: LOCATION_ID_NOT_FOUND: The Location: "ALTU" does not exist.
ORA-06512: at "CWMS_20.CWMS_ERR", line 59
ORA-06512: at "CWMS_20.CWMS_LOC", line 128
ORA-01403: no data found
ORA-06512: at "CWMS_20.CWMS_LOC", line 115
ORA-01403: no data found
ORA-06512: at "CWMS_20.CWMS_LOC", line 91
ORA-06512: at "CWMS_20.CWMS_TS", line 9873
ORA-01403: no data found
ORA-06512: at "CWMS_20.CWMS_TS", line 9855
ORA-06512: at "CWMS_20.CWMS_TS", line 131
ORA-01403: no data found
ORA-06512: at "CWMS_20.CWMS_TS", line 120
ORA-06512: at "CWMS_20.CWMS_TS", line 41
ORA-06512: at "CWMS_20.CWMS_TS", line 26
ORA-06512: at "CWMS_20.CWMS_TS", line 9923

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:513)
	... 61 more


```

**Comment by rripken** [comment]
This did not duplicate for me just now.  Not sure when or if it got fixed.

**Comment by rripken** [comment]
I look at the vertical datum offsets also.   The pl/sql returns this xml snippet for the vertical datum:
```
<vertical-datum-info office="SWT" unit="m">
<location>ARBU</location>
<native-datum>NGVD-29</native-datum>
<elevation>243.8</elevation>
<offset estimate="true">
<to-datum>NAVD-88</to-datum>
<value>0.0632</value>
</offset>
</vertical-datum-info>
```

In the json response I see this corresponding section:
```
"offsets": [
  {
    "estimate": true,
    "to-datum": "NAVD-88",
    "value": 0.0632
  }
]
```

**Comment by adamkorynta** [comment]
I think you missed the code formatting on that comment
