### ISSUE TITLE
Retrieving levels with "*" wildcard throws a System Error

### ISSUE THREAD

**Issue by adamkorynta** [USACE/cwms-data-api#111]
Example cURL:
```
curl -X 'GET' \
  'http://localhost:11524/cwms-data/levels?name=%2A' \
  -H 'accept: */*'
```

Server-side error:
```
Nov 18, 2021 4:20:54 PM cwms.radar.ApiServlet lambda$init$9
WARNING: error on request[-446897415283128917]: /cwms-data/levels
org.jooq.exception.DataAccessException: SQL [{ ? = call "CWMS_20"."CWMS_LEVEL"."RETRIEVE_LOCATION_LEVELS_F" (?, ?, ?, ?, ?, ?, ?, ?) }]; ORA-20998: ERROR: ORA-06512: at "CWMS_20.CWMS_LEVEL", line 10564
ORA-06512: at "CWMS_20.CWMS_ERR", line 59
ORA-06512: at "CWMS_20.CWMS_LEVEL", line 11051
ORA-01426: numeric overflow
ORA-06512: at "CWMS_20.CWMS_LEVEL", line 10564
ORA-06512: at "CWMS_20.CWMS_LEVEL", line 9333
ORA-06512: at line 1

	at org.jooq_3.11.2.ORACLE11G.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:2380)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:811)
	at org.jooq.impl.AbstractRoutine.executeCallableStatement(AbstractRoutine.java:510)
	at org.jooq.impl.AbstractRoutine.execute(AbstractRoutine.java:391)
	at org.jooq.impl.AbstractRoutine.execute(AbstractRoutine.java:321)
	at usace.cwms.db.jooq.codegen.packages.CWMS_LEVEL_PACKAGE.call_RETRIEVE_LOCATION_LEVELS_F(CWMS_LEVEL_PACKAGE.java:1557)
	at cwms.radar.data.CwmsDataManager.getLocationLevels(CwmsDataManager.java:60)
	at cwms.radar.api.LevelsController.getAll(LevelsController.java:219)
	at io.javalin.apibuilder.CrudFunction$1.invoke$lambda-0(CrudHandler.kt:30)
	at io.javalin.apibuilder.CrudFunctionHandler.handle(CrudHandler.kt)
	at io.javalin.core.security.SecurityUtil.noopAccessManager(SecurityUtil.kt:20)
	at io.javalin.http.JavalinServlet.addHandler$lambda-5(JavalinServlet.kt:113)
	at io.javalin.http.JavalinServlet$service$tryBeforeAndEndpointHandlers$1.invoke(JavalinServlet.kt:44)
	at io.javalin.http.JavalinServlet$service$tryBeforeAndEndpointHandlers$1.invoke(JavalinServlet.kt:39)
	at io.javalin.http.JavalinServlet.service$tryWithExceptionMapper(JavalinServlet.kt:129)
	at io.javalin.http.JavalinServlet.service$tryBeforeAndEndpointHandlers(JavalinServlet.kt:39)
	at io.javalin.http.JavalinServlet.service(JavalinServlet.kt:87)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at cwms.radar.ApiServlet.service(ApiServlet.java:205)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:895)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1722)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: ORA-20998: ERROR: ORA-06512: at "CWMS_20.CWMS_LEVEL", line 10564
ORA-06512: at "CWMS_20.CWMS_ERR", line 59
ORA-06512: at "CWMS_20.CWMS_LEVEL", line 11051
ORA-01426: numeric overflow
ORA-06512: at "CWMS_20.CWMS_LEVEL", line 10564
ORA-06512: at "CWMS_20.CWMS_LEVEL", line 9333
ORA-06512: at line 1

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:509)
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:461)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1104)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:550)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:268)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:655)
	at oracle.jdbc.driver.T4CCallableStatement.doOall8(T4CCallableStatement.java:265)
	at oracle.jdbc.driver.T4CCallableStatement.doOall8(T4CCallableStatement.java:86)
	at oracle.jdbc.driver.T4CCallableStatement.executeForRows(T4CCallableStatement.java:965)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1205)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3666)
	at oracle.jdbc.driver.T4CCallableStatement.executeInternal(T4CCallableStatement.java:1358)
	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3778)
	at oracle.jdbc.driver.OracleCallableStatement.execute(OracleCallableStatement.java:4251)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1081)
	at sun.reflect.GeneratedMethodAccessor36.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:118)
	at com.sun.proxy.$Proxy8.execute(Unknown Source)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:209)
	at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:3416)
	at org.jooq.impl.AbstractRoutine.execute0(AbstractRoutine.java:521)
	at org.jooq.impl.AbstractRoutine.executeCallableStatement(AbstractRoutine.java:481)
	... 35 more
Caused by: Error : 20998, Position : 0, Sql = BEGIN :1 := "CWMS_20"."CWMS_LEVEL"."RETRIEVE_LOCATION_LEVELS_F" (:2 , :3 , :4 , :5 , :6 , :7 , :8 , :9 ) ; END;, OriginalSql = { ? = call "CWMS_20"."CWMS_LEVEL"."RETRIEVE_LOCATION_LEVELS_F" (?, ?, ?, ?, ?, ?, ?, ?) }, Error Msg = ORA-20998: ERROR: ORA-06512: at "CWMS_20.CWMS_LEVEL", line 10564
ORA-06512: at "CWMS_20.CWMS_ERR", line 59
ORA-06512: at "CWMS_20.CWMS_LEVEL", line 11051
ORA-01426: numeric overflow
ORA-06512: at "CWMS_20.CWMS_LEVEL", line 10564
ORA-06512: at "CWMS_20.CWMS_LEVEL", line 9333
ORA-06512: at line 1

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:513)
	... 58 more
```

**Comment by MikeNeilson** [comment]
```
ORA-06512: at "CWMS_20.CWMS_ERR", line 59
ORA-06512: at "CWMS_20.CWMS_LEVEL", line 11051
ORA-01426: numeric overflow  <-------------------------- This appears to be problematic... but also in the database.
ORA-06512: at "CWMS_20.CWMS_LEVEL", line 10564
ORA-06512: at "CWMS_20.CWMS_LEVEL", line 9333
ORA-06512: at line 1

```

**Comment by rripken** [comment]
This is the line where that overflow happens:
`l_code := cwms_loc.get_location_code(l_lvlids(i).office, l_parts(1));`
l_code was declared pls_integer  but get_location_code returns number.

Confirmed that the database where this was happening has a huge location_code (e.g. 9772029451)

**Comment by rripken** [comment]
l_code just needs to be "integer" or even number(14,0) and not "pls_integer"

**Comment by rripken** [comment]
Even better:
 l_code             at_physical_location.location_code%TYPE;

**Comment by rripken** [comment]
I was able to apply the above change on a local database and no longer get the overflow exception.   Unfortunately I now see an error that resembles #157 but its progress.

**Comment by rripken** [comment]
https://bitbucket.hecdev.net/projects/CWMS/repos/cwms_database/pull-requests/197/
