### ISSUE TITLE
catalog/timeseries ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by adamkorynta** [USACE/cwms-data-api#118]
Ran into this issue performing the following (no filtering for tsid, category, group, etc):

Retrieve with page size of 500
Using the next-page cursor I then retrieved a page size of (the returned total count - 500) in order to get the full catalog
The returned result gave me another next-page cursor so I again tried to retrieved a page size of (the returned total count - 500) assuming there was an identifier that was somehow missed in the earlier retrieve.

Stack Trace:

```
WARNING: error on request[-7206020114998510233]: /cwms-data/catalog/timeseries
java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:424)
	at java.util.ArrayList.get(ArrayList.java:437)
	at cwms.radar.data.dto.Catalog.<init>(Catalog.java:37)
	at cwms.radar.data.dao.TimeSeriesDaoImpl.getTimeSeriesCatalog(TimeSeriesDaoImpl.java:428)
	at cwms.radar.api.CatalogController.getOne(CatalogController.java:154)
	at io.javalin.apibuilder.CrudFunction$2.invoke$lambda-0(CrudHandler.kt:31)
	at io.javalin.apibuilder.CrudFunctionHandler.handle(CrudHandler.kt)
	at io.javalin.core.security.SecurityUtil.noopAccessManager(SecurityUtil.kt:20)
	at io.javalin.http.JavalinServlet.addHandler$lambda-5(JavalinServlet.kt:113)
	at io.javalin.http.JavalinServlet$service$tryBeforeAndEndpointHandlers$1.invoke(JavalinServlet.kt:44)
	at io.javalin.http.JavalinServlet$service$tryBeforeAndEndpointHandlers$1.invoke(JavalinServlet.kt:39)
	at io.javalin.http.JavalinServlet.service$tryWithExceptionMapper(JavalinServlet.kt:129)
	at io.javalin.http.JavalinServlet.service$tryBeforeAndEndpointHandlers(JavalinServlet.kt:39)
	at io.javalin.http.JavalinServlet.service(JavalinServlet.kt:87)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at cwms.radar.ApiServlet.service(ApiServlet.java:205)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:895)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1722)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by MikeNeilson** [comment]
where you trying to alter the page size on the next call? You should just pass in the next page variable, you shouldn't need to set the page size again. 

I'll look into it as it should have a better error message, but my initial inclination is "why are you doing it that way?"

**Comment by adamkorynta** [comment]
I've started a discussion to figure out the optimal way to pull the entire time series catalog here: https://github.com/USACE/cwms-radar-api/discussions/120 that describes the usage of variable page sizes.

**Comment by rripken** [comment]
Last I heard, the page sizes are now consistent but the full ts catalog has not been run from CWMSVue to see if performance is good enough.
