### ISSUE TITLE
location/category/{category-id} API broken if category has more than one time series group

### ISSUE THREAD

**Issue by adamkorynta** [USACE/cwms-data-api#124]
cURL Example:

```
curl -X 'GET' \
  'http://localhost:11524/cwms-data/location/category/RDL_Basins?office=SWT' \
  -H 'accept: application/json'
```

Response:
```
{
  "message": "System Error",
  "incidentIdentifier": "-279359216340917649",
  "details": {}
}
Response headers
 connection: close 
 content-length: 82 
 content-type: application/json;charset=UTF-8 
 date: Fri,03 Dec 2021 23:58:11 GMT 
 x-content-type-options: nosniff 
 x-frame-options: SAMEORIGIN 
 x-ss-protection: 1; mode=block 
```

Server-side exception:

```
Dec 03, 2021 3:58:11 PM cwms.radar.ApiServlet lambda$init$9
WARNING: error on request[-279359216340917649]: /cwms-data/location/category/RDL_Basins
org.jooq.exception.TooManyRowsException: Cursor returned more than one result
	at org.jooq.impl.Tools.fetchOne(Tools.java:1770)
	at org.jooq.impl.AbstractResultQuery.fetchOne(AbstractResultQuery.java:545)
	at org.jooq.impl.SelectImpl.fetchOne(SelectImpl.java:2879)
	at cwms.radar.data.dao.LocationCategoryDao.getLocationCategory(LocationCategoryDao.java:54)
	at cwms.radar.api.LocationCategoryController.getOne(LocationCategoryController.java:128)
	at io.javalin.apibuilder.CrudFunction$2.invoke$lambda-0(CrudHandler.kt:31)
	at io.javalin.apibuilder.CrudFunctionHandler.handle(CrudHandler.kt)
	at io.javalin.core.security.SecurityUtil.noopAccessManager(SecurityUtil.kt:20)
	at io.javalin.http.JavalinServlet.addHandler$lambda-5(JavalinServlet.kt:113)
	at io.javalin.http.JavalinServlet$service$tryBeforeAndEndpointHandlers$1.invoke(JavalinServlet.kt:44)
	at io.javalin.http.JavalinServlet$service$tryBeforeAndEndpointHandlers$1.invoke(JavalinServlet.kt:39)
	at io.javalin.http.JavalinServlet.service$tryWithExceptionMapper(JavalinServlet.kt:129)
	at io.javalin.http.JavalinServlet.service$tryBeforeAndEndpointHandlers(JavalinServlet.kt:39)
	at io.javalin.http.JavalinServlet.service(JavalinServlet.kt:87)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at cwms.radar.ApiServlet.service(ApiServlet.java:205)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:895)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1722)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)


```

**Comment by rripken** [comment]
Was missing a selectDistinct.  Not sure how I did all the other LocationCategory and TimeSeriesCategory methods and missed this one. #125

**Comment by adamkorynta** [comment]
Confirmed working
