### ISSUE TITLE
Unable to retrieve data for time series and location category/group API's

### ISSUE THREAD

**Issue by adamkorynta** [USACE/cwms-data-api#158]
I'm guessing all the issues are the same root cause.

Returned to the client:

 Request{method=GET, url=http://localhost:11526/cwms-data/timeseries/group?office=NAB, headers=[accept:application/json]}
 Error code: 501 
{"message":"Formatting error","incidentIdentifier":"-2216357029092516105","details":{}}

Request{method=GET, url=http://localhost:11526/cwms-data/timeseries/category/TestName5369063?office=NAB, headers=[accept:application/json]}
 Error code: 501 
{"message":"Formatting error","incidentIdentifier":"-6053718998278363873","details":{}}

Request{method=GET, url=http://localhost:11526/cwms-data/timeseries/category/TestName5369063?office=NAB, headers=[accept:application/json]}
 Error code: 501 
{"message":"Formatting error","incidentIdentifier":"-6053718998278363873","details":{}}

An example stack trace from the server side:
SEVERE: -6462912231379889787: Formatting errorfor request: https://localhost:11526/cwms-data/location/category?office=NAB
cwms.radar.formatters.FormattingException: Accept header and query parameter are both present, this is not supported.
	at cwms.radar.formatters.Formats.parseHeaderAndQueryParm(Formats.java:180)
	at cwms.radar.api.LocationCategoryController.getAll(LocationCategoryController.java:79)
	at io.javalin.apibuilder.CrudFunction$1.invoke$lambda-0(CrudHandler.kt:30)
	at io.javalin.apibuilder.CrudFunctionHandler.handle(CrudHandler.kt)
	at cwms.radar.security.CwmsAccessManager.manage(CwmsAccessManager.java:45)
	at io.javalin.http.JavalinServlet.addHandler$lambda-5(JavalinServlet.kt:113)
	at io.javalin.http.JavalinServlet$service$tryBeforeAndEndpointHandlers$1.invoke(JavalinServlet.kt:44)
	at io.javalin.http.JavalinServlet$service$tryBeforeAndEndpointHandlers$1.invoke(JavalinServlet.kt:39)
	at io.javalin.http.JavalinServlet.service$tryWithExceptionMapper(JavalinServlet.kt:129)
	at io.javalin.http.JavalinServlet.service$tryBeforeAndEndpointHandlers(JavalinServlet.kt:39)
	at io.javalin.http.JavalinServlet.service(JavalinServlet.kt:87)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at cwms.radar.ApiServlet.service(ApiServlet.java:291)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:895)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1722)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

**Comment by rripken** [comment]
This looks to be happening because some usages of parseHeaderAndQueryParm were treating the query param field as a default.  If the user didn't specify anything in the accept header the code assumed they wanted json.   The parseHeaderAndQueryParm method was later changed to throw an exception if both format query param and an accept header were specified.
I can make it so parseHeaderAndQueryParm can take a third arg that would allow the old behavior where there is an assumed default format.  But it doesn't seem that burdensome on users to remove the defaults and require users to specify the format they want, even if there is only one choice.  
Thoughts?

**Comment by MikeNeilson** [comment]
I say enforce the mutually exclusive behavior but make sure there's a good error message that propagates out to the user. I think now.

**Comment by rripken** [comment]
The issues isn't the mutually exclusive behavior.  At least not in the sense I think you mean.  Adam's examples only have one format specified.  Several controllers had hardcoded "json" as the query param so that if no accept-header was provided json would be used.   I'm voting for removing those hardcoded "json" args.  For those controllers the user must provide the desired format in the accept-header.  This won't affect the older Controllers that can take either accept-header or format query param.

**Comment by MikeNeilson** [comment]
yep, I read that wrong. But I'm in agreement with your plan.
