### ISSUE TITLE
Unable to retrieve time series "single-row subquery returns more than one row"

### ISSUE THREAD

**Issue by adamkorynta** [USACE/cwms-data-api#162]
Server-side error:
```
WARNING: error on request[-7985744130827073432]: /cwms-data/timeseries
org.jooq.exception.DataAccessException: SQL [select "CWMS_20"."CWMS_TS"."GET_TS_ID"(?, "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"(?)) "NAME", "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"(?) "OFFICE_ID", "CWMS_20"."CWMS_UTIL"."GET_DEFAULT_UNITS"("CWMS_20"."CWMS_TS"."GET_BASE_PARAMETER_ID"("CWMS_20"."CWMS_TS"."GET_TS_CODE"("CWMS_20"."CWMS_TS"."GET_TS_ID"(?, "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"(?)), "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"(?))), ?) "UNITS", "CWMS_20"."CWMS_TS"."GET_INTERVAL"("CWMS_20"."CWMS_TS"."GET_TS_ID"(?, "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"(?))) "INTERVAL", "CWMS_20"."CWMS_UTIL"."SPLIT_TEXT"("CWMS_20"."CWMS_TS"."GET_TS_ID"(?, "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"(?)), ?, ?, ?) "LOC_PART", upper("CWMS_20"."CWMS_UTIL"."SPLIT_TEXT"("CWMS_20"."CWMS_TS"."GET_TS_ID"(?, "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"(?)), ?, ?, ?)) "PARM_PART", case upper("CWMS_20"."CWMS_UTIL"."SPLIT_TEXT"("CWMS_20"."CWMS_TS"."GET_TS_ID"(?, "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"(?)), ?, ?, ?)) when ? then "CWMS_20"."CWMS_LOC"."GET_VERTICAL_DATUM_INFO_F"("CWMS_20"."CWMS_UTIL"."SPLIT_TEXT"("CWMS_20"."CWMS_TS"."GET_TS_ID"(?, "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"(?)), ?, ?, ?), "CWMS_20"."CWMS_UTIL"."GET_DEFAULT_UNITS"("CWMS_20"."CWMS_TS"."GET_BASE_PARAMETER_ID"("CWMS_20"."CWMS_TS"."GET_TS_CODE"("CWMS_20"."CWMS_TS"."GET_TS_ID"(?, "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"(?)), "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"(?))), ?), "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"(?)) else ? end "VERTICAL_DATUM", (select count(*) from table("CWMS_20"."CWMS_TS"."RETRIEVE_TS_OUT_TAB"(
  "CWMS_20"."CWMS_TS"."GET_TS_ID"(
    'COUG.Flow.Ave.~1Day.1Day.Ccp-Rev', 
    "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"('SWT')
  ), 
  "CWMS_20"."CWMS_UTIL"."GET_DEFAULT_UNITS"(
    "CWMS_20"."CWMS_TS"."GET_BASE_PARAMETER_ID"("CWMS_20"."CWMS_TS"."GET_TS_CODE"(
      "CWMS_20"."CWMS_TS"."GET_TS_ID"(
        'COUG.Flow.Ave.~1Day.1Day.Ccp-Rev', 
        "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"('SWT')
      ), 
      "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"('SWT')
    )), 
    'SI'
  ), 
  "CWMS_20"."CWMS_UTIL"."TO_TIMESTAMP"(666070500000), 
  "CWMS_20"."CWMS_UTIL"."TO_TIMESTAMP"(1540161300000), 
  'UTC', 
  null, 
  null, 
  null, 
  null, 
  null, 
  null, 
  null, 
  "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"('SWT')
))) "TOTAL", (select "CWMS_20"."AV_CWMS_TS_ID2"."INTERVAL_UTC_OFFSET" "INTERVAL_UTC_OFFSET" from "CWMS_20"."AV_CWMS_TS_ID2" where "CWMS_20"."AV_CWMS_TS_ID2"."CWMS_TS_ID" = "CWMS_20"."CWMS_TS"."GET_TS_ID"(?, "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"(?))), (select "CWMS_20"."AV_CWMS_TS_ID2"."TIME_ZONE_ID" from "CWMS_20"."AV_CWMS_TS_ID2" where "CWMS_20"."AV_CWMS_TS_ID2"."CWMS_TS_ID" = "CWMS_20"."CWMS_TS"."GET_TS_ID"(?, "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"(?))) "TIME_ZONE_ID" from dual]; ORA-01427: single-row subquery returns more than one row

	at org.jooq_3.11.2.ORACLE11G.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:2380)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:811)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:364)
	at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:393)
	at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:380)
	at org.jooq.impl.AbstractResultQuery.fetchOne(AbstractResultQuery.java:545)
	at org.jooq.impl.AbstractResultQuery.fetchOne(AbstractResultQuery.java:550)
	at org.jooq.impl.SelectImpl.fetchOne(SelectImpl.java:2884)
	at cwms.radar.data.dao.TimeSeriesDaoImpl.getTimeseries(TimeSeriesDaoImpl.java:241)
	at cwms.radar.data.dao.TimeSeriesDaoImpl.getTimeseries(TimeSeriesDaoImpl.java:117)
	at cwms.radar.api.TimeSeriesController.getAll(TimeSeriesController.java:257)
	at io.javalin.apibuilder.CrudFunction$1.invoke$lambda-0(CrudHandler.kt:30)
	at io.javalin.apibuilder.CrudFunctionHandler.handle(CrudHandler.kt)
	at cwms.radar.security.CwmsAccessManager.manage(CwmsAccessManager.java:45)
	at io.javalin.http.JavalinServlet.addHandler$lambda-5(JavalinServlet.kt:113)
	at io.javalin.http.JavalinServlet$service$tryBeforeAndEndpointHandlers$1.invoke(JavalinServlet.kt:44)
	at io.javalin.http.JavalinServlet$service$tryBeforeAndEndpointHandlers$1.invoke(JavalinServlet.kt:39)
	at io.javalin.http.JavalinServlet.service$tryWithExceptionMapper(JavalinServlet.kt:129)
	at io.javalin.http.JavalinServlet.service$tryBeforeAndEndpointHandlers(JavalinServlet.kt:39)
	at io.javalin.http.JavalinServlet.service(JavalinServlet.kt:87)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at cwms.radar.ApiServlet.service(ApiServlet.java:291)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:895)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1722)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: ORA-01427: single-row subquery returns more than one row

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:509)
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:461)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1104)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:550)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:268)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:655)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:270)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:91)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:807)
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:983)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1168)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3666)
	at oracle.jdbc.driver.T4CPreparedStatement.executeInternal(T4CPreparedStatement.java:1426)
	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3778)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1081)
	at sun.reflect.GeneratedMethodAccessor48.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:118)
	at com.sun.proxy.$Proxy9.execute(Unknown Source)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:209)
	at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:3416)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:268)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:350)
	... 38 more
Caused by: Error : 1427, Position : 2380, Sql = select "CWMS_20"."CWMS_TS"."GET_TS_ID"(:1 , "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"(:2 )) "NAME", "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"(:3 ) "OFFICE_ID", "CWMS_20"."CWMS_UTIL"."GET_DEFAULT_UNITS"("CWMS_20"."CWMS_TS"."GET_BASE_PARAMETER_ID"("CWMS_20"."CWMS_TS"."GET_TS_CODE"("CWMS_20"."CWMS_TS"."GET_TS_ID"(:4 , "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"(:5 )), "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"(:6 ))), :7 ) "UNITS", "CWMS_20"."CWMS_TS"."GET_INTERVAL"("CWMS_20"."CWMS_TS"."GET_TS_ID"(:8 , "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"(:9 ))) "INTERVAL", "CWMS_20"."CWMS_UTIL"."SPLIT_TEXT"("CWMS_20"."CWMS_TS"."GET_TS_ID"(:10 , "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"(:11 )), :12 , :13 , :14 ) "LOC_PART", upper("CWMS_20"."CWMS_UTIL"."SPLIT_TEXT"("CWMS_20"."CWMS_TS"."GET_TS_ID"(:15 , "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"(:16 )), :17 , :18 , :19 )) "PARM_PART", case upper("CWMS_20"."CWMS_UTIL"."SPLIT_TEXT"("CWMS_20"."CWMS_TS"."GET_TS_ID"(:20 , "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"(:21 )), :22 , :23 , :24 )) when :25  then "CWMS_20"."CWMS_LOC"."GET_VERTICAL_DATUM_INFO_F"("CWMS_20"."CWMS_UTIL"."SPLIT_TEXT"("CWMS_20"."CWMS_TS"."GET_TS_ID"(:26 , "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"(:27 )), :28 , :29 , :30 ), "CWMS_20"."CWMS_UTIL"."GET_DEFAULT_UNITS"("CWMS_20"."CWMS_TS"."GET_BASE_PARAMETER_ID"("CWMS_20"."CWMS_TS"."GET_TS_CODE"("CWMS_20"."CWMS_TS"."GET_TS_ID"(:31 , "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"(:32 )), "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"(:33 ))), :34 ), "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"(:35 )) else :36  end "VERTICAL_DATUM", (select count(*) from table("CWMS_20"."CWMS_TS"."RETRIEVE_TS_OUT_TAB"(
  "CWMS_20"."CWMS_TS"."GET_TS_ID"(
    'COUG.Flow.Ave.~1Day.1Day.Ccp-Rev', 
    "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"('SWT')
  ), 
  "CWMS_20"."CWMS_UTIL"."GET_DEFAULT_UNITS"(
    "CWMS_20"."CWMS_TS"."GET_BASE_PARAMETER_ID"("CWMS_20"."CWMS_TS"."GET_TS_CODE"(
      "CWMS_20"."CWMS_TS"."GET_TS_ID"(
        'COUG.Flow.Ave.~1Day.1Day.Ccp-Rev', 
        "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"('SWT')
      ), 
      "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"('SWT')
    )), 
    'SI'
  ), 
  "CWMS_20"."CWMS_UTIL"."TO_TIMESTAMP"(666070500000), 
  "CWMS_20"."CWMS_UTIL"."TO_TIMESTAMP"(1540161300000), 
  'UTC', 
  null, 
  null, 
  null, 
  null, 
  null, 
  null, 
  null, 
  "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"('SWT')
))) "TOTAL", (select "CWMS_20"."AV_CWMS_TS_ID2"."INTERVAL_UTC_OFFSET" "INTERVAL_UTC_OFFSET" from "CWMS_20"."AV_CWMS_TS_ID2" where "CWMS_20"."AV_CWMS_TS_ID2"."CWMS_TS_ID" = "CWMS_20"."CWMS_TS"."GET_TS_ID"(:37 , "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"(:38 ))), (select "CWMS_20"."AV_CWMS_TS_ID2"."TIME_ZONE_ID" from "CWMS_20"."AV_CWMS_TS_ID2" where "CWMS_20"."AV_CWMS_TS_ID2"."CWMS_TS_ID" = "CWMS_20"."CWMS_TS"."GET_TS_ID"(:39 , "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"(:40 ))) "TIME_ZONE_ID" from dual, OriginalSql = select "CWMS_20"."CWMS_TS"."GET_TS_ID"(?, "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"(?)) "NAME", "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"(?) "OFFICE_ID", "CWMS_20"."CWMS_UTIL"."GET_DEFAULT_UNITS"("CWMS_20"."CWMS_TS"."GET_BASE_PARAMETER_ID"("CWMS_20"."CWMS_TS"."GET_TS_CODE"("CWMS_20"."CWMS_TS"."GET_TS_ID"(?, "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"(?)), "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"(?))), ?) "UNITS", "CWMS_20"."CWMS_TS"."GET_INTERVAL"("CWMS_20"."CWMS_TS"."GET_TS_ID"(?, "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"(?))) "INTERVAL", "CWMS_20"."CWMS_UTIL"."SPLIT_TEXT"("CWMS_20"."CWMS_TS"."GET_TS_ID"(?, "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"(?)), ?, ?, ?) "LOC_PART", upper("CWMS_20"."CWMS_UTIL"."SPLIT_TEXT"("CWMS_20"."CWMS_TS"."GET_TS_ID"(?, "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"(?)), ?, ?, ?)) "PARM_PART", case upper("CWMS_20"."CWMS_UTIL"."SPLIT_TEXT"("CWMS_20"."CWMS_TS"."GET_TS_ID"(?, "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"(?)), ?, ?, ?)) when ? then "CWMS_20"."CWMS_LOC"."GET_VERTICAL_DATUM_INFO_F"("CWMS_20"."CWMS_UTIL"."SPLIT_TEXT"("CWMS_20"."CWMS_TS"."GET_TS_ID"(?, "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"(?)), ?, ?, ?), "CWMS_20"."CWMS_UTIL"."GET_DEFAULT_UNITS"("CWMS_20"."CWMS_TS"."GET_BASE_PARAMETER_ID"("CWMS_20"."CWMS_TS"."GET_TS_CODE"("CWMS_20"."CWMS_TS"."GET_TS_ID"(?, "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"(?)), "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"(?))), ?), "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"(?)) else ? end "VERTICAL_DATUM", (select count(*) from table("CWMS_20"."CWMS_TS"."RETRIEVE_TS_OUT_TAB"(
  "CWMS_20"."CWMS_TS"."GET_TS_ID"(
    'COUG.Flow.Ave.~1Day.1Day.Ccp-Rev', 
    "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"('SWT')
  ), 
  "CWMS_20"."CWMS_UTIL"."GET_DEFAULT_UNITS"(
    "CWMS_20"."CWMS_TS"."GET_BASE_PARAMETER_ID"("CWMS_20"."CWMS_TS"."GET_TS_CODE"(
      "CWMS_20"."CWMS_TS"."GET_TS_ID"(
        'COUG.Flow.Ave.~1Day.1Day.Ccp-Rev', 
        "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"('SWT')
      ), 
      "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"('SWT')
    )), 
    'SI'
  ), 
  "CWMS_20"."CWMS_UTIL"."TO_TIMESTAMP"(666070500000), 
  "CWMS_20"."CWMS_UTIL"."TO_TIMESTAMP"(1540161300000), 
  'UTC', 
  null, 
  null, 
  null, 
  null, 
  null, 
  null, 
  null, 
  "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"('SWT')
))) "TOTAL", (select "CWMS_20"."AV_CWMS_TS_ID2"."INTERVAL_UTC_OFFSET" "INTERVAL_UTC_OFFSET" from "CWMS_20"."AV_CWMS_TS_ID2" where "CWMS_20"."AV_CWMS_TS_ID2"."CWMS_TS_ID" = "CWMS_20"."CWMS_TS"."GET_TS_ID"(?, "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"(?))), (select "CWMS_20"."AV_CWMS_TS_ID2"."TIME_ZONE_ID" from "CWMS_20"."AV_CWMS_TS_ID2" where "CWMS_20"."AV_CWMS_TS_ID2"."CWMS_TS_ID" = "CWMS_20"."CWMS_TS"."GET_TS_ID"(?, "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"(?))) "TIME_ZONE_ID" from dual, Error Msg = ORA-01427: single-row subquery returns more than one row

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:513)
	... 61 more
```

Client side:
```
Caused by: java.io.IOException: Unknown error occurred for request: Request{method=GET, url=http://localhost:11526/cwms-data/timeseries?unit=SI&timezone=UTC&name=COUG.Flow.Ave.%7E1Day.1Day.Ccp-Rev&pageSize=100&end=2018-10-21T22%3A35%3A00Z&office=SWT&begin=1991-02-09T03%3A35%3A00Z, headers=[accept:application/json;version=2]}
 Error code: 500 
{"message":"System Error","incidentIdentifier":"-8558424849125800083","details":{}}
	at mil.army.usace.hec.cwms.http.client.HttpRequestBuilderImpl$HttpRequestExecutorImpl.checkError(HttpRequestBuilderImpl.java:201)
	at mil.army.usace.hec.cwms.http.client.HttpRequestBuilderImpl$HttpRequestExecutorImpl.handleExecutionError(HttpRequestBuilderImpl.java:182)
	at mil.army.usace.hec.cwms.http.client.HttpRequestBuilderImpl$HttpRequestExecutorImpl.execute(HttpRequestBuilderImpl.java:172)
	at mil.army.usace.hec.cwms.radar.client.controllers.TimeSeriesController.retrieveTimeSeries(TimeSeriesController.java:48)
	at wcds.dbi.cwms.radar.CwmsTimeSeriesRadarDao.retrieveTimeSeries(CwmsTimeSeriesRadarDao.java:162)
	... 7 more
```

**Comment by adamkorynta** [comment]
Here's the resolved query:

```
select "CWMS_20"."CWMS_TS"."GET_TS_ID"('BURL.Flow.Ave.~1Day.1Day.Ccp-Rev', "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"('SWT')) "NAME", "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"('SWT') "OFFICE_ID", "CWMS_20"."CWMS_UTIL"."GET_DEFAULT_UNITS"("CWMS_20"."CWMS_TS"."GET_BASE_PARAMETER_ID"("CWMS_20"."CWMS_TS"."GET_TS_CODE"("CWMS_20"."CWMS_TS"."GET_TS_ID"('BURL.Flow.Ave.~1Day.1Day.Ccp-Rev', "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"('SWT')), "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"('SWT'))), 'SI') "UNITS", "CWMS_20"."CWMS_TS"."GET_INTERVAL"("CWMS_20"."CWMS_TS"."GET_TS_ID"('BURL.Flow.Ave.~1Day.1Day.Ccp-Rev', "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"('SWT'))) "INTERVAL", "CWMS_20"."CWMS_UTIL"."SPLIT_TEXT"("CWMS_20"."CWMS_TS"."GET_TS_ID"('BURL.Flow.Ave.~1Day.1Day.Ccp-Rev', "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"('SWT')), 1, '.', 6) "LOC_PART", upper("CWMS_20"."CWMS_UTIL"."SPLIT_TEXT"("CWMS_20"."CWMS_TS"."GET_TS_ID"('BURL.Flow.Ave.~1Day.1Day.Ccp-Rev', "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"('SWT')), 2, '.', 6)) "PARM_PART", case upper("CWMS_20"."CWMS_UTIL"."SPLIT_TEXT"("CWMS_20"."CWMS_TS"."GET_TS_ID"('BURL.Flow.Ave.~1Day.1Day.Ccp-Rev', "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"('SWT')), 2, '.', 6)) when 'ELEV' then "CWMS_20"."CWMS_LOC"."GET_VERTICAL_DATUM_INFO_F"("CWMS_20"."CWMS_UTIL"."SPLIT_TEXT"("CWMS_20"."CWMS_TS"."GET_TS_ID"('BURL.Flow.Ave.~1Day.1Day.Ccp-Rev', "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"('SWT')), 1, '.', 6), "CWMS_20"."CWMS_UTIL"."GET_DEFAULT_UNITS"("CWMS_20"."CWMS_TS"."GET_BASE_PARAMETER_ID"("CWMS_20"."CWMS_TS"."GET_TS_CODE"("CWMS_20"."CWMS_TS"."GET_TS_ID"('BURL.Flow.Ave.~1Day.1Day.Ccp-Rev', "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"('SWT')), "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"('SWT'))), 'SI'), "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"('SWT')) else '' end "VERTICAL_DATUM", (select count(*) from table("CWMS_20"."CWMS_TS"."RETRIEVE_TS_OUT_TAB"(
  "CWMS_20"."CWMS_TS"."GET_TS_ID"(
    'BURL.Flow.Ave.~1Day.1Day.Ccp-Rev',
    "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"('SWT')
  ),
  "CWMS_20"."CWMS_UTIL"."GET_DEFAULT_UNITS"(
    "CWMS_20"."CWMS_TS"."GET_BASE_PARAMETER_ID"("CWMS_20"."CWMS_TS"."GET_TS_CODE"(
      "CWMS_20"."CWMS_TS"."GET_TS_ID"(
        'BURL.Flow.Ave.~1Day.1Day.Ccp-Rev',
        "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"('SWT')
      ),
      "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"('SWT')
    )),
    'SI'
  ),
  "CWMS_20"."CWMS_UTIL"."TO_TIMESTAMP"(666070500000),
  "CWMS_20"."CWMS_UTIL"."TO_TIMESTAMP"(1540161300000),
  'UTC',
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"('SWT')
))) "TOTAL", (select "CWMS_20"."AV_CWMS_TS_ID2"."INTERVAL_UTC_OFFSET" "INTERVAL_UTC_OFFSET" from "CWMS_20"."AV_CWMS_TS_ID2" where "CWMS_20"."AV_CWMS_TS_ID2"."CWMS_TS_ID" = "CWMS_20"."CWMS_TS"."GET_TS_ID"('BURL.Flow.Ave.~1Day.1Day.Ccp-Rev', "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"('SWT'))), (select "CWMS_20"."AV_CWMS_TS_ID2"."TIME_ZONE_ID" from "CWMS_20"."AV_CWMS_TS_ID2" where "CWMS_20"."AV_CWMS_TS_ID2"."CWMS_TS_ID" = "CWMS_20"."CWMS_TS"."GET_TS_ID"('BURL.Flow.Ave.~1Day.1Day.Ccp-Rev', "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"('SWT'))) "TIME_ZONE_ID" from dual
```

**Comment by rripken** [comment]
I saw that this sub-query returns 3 rows
select "CWMS_20"."AV_CWMS_TS_ID2"."INTERVAL_UTC_OFFSET" "INTERVAL_UTC_OFFSET"
        from "CWMS_20"."AV_CWMS_TS_ID2"
        where "CWMS_20"."AV_CWMS_TS_ID2"."CWMS_TS_ID" =
              "CWMS_20"."CWMS_TS"."GET_TS_ID"('BURL.Flow.Ave.~1Day.1Day.Ccp-Rev',
                                              "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"('SWT')) )

It needs an aliased item check
...and "CWMS_20"."AV_CWMS_TS_ID2".ALIASED_ITEM is null

Same for the tzName subquery

**Comment by MikeNeilson** [comment]
this got fixed as part of the performance regression fix. The pull of the offset and tzname were put in a join and the aliased_item null check is present.
