### ISSUE TITLE
Time Series retrieval fails without supplying an Office Id

### ISSUE THREAD

**Issue by adamkorynta** [USACE/cwms-data-api#171]
Currently if I do not supply an Office Id in the time series retrieval request, I get a no data found message. This used to work previously and the documentation states that it should (albeit with a location level typo)
```
Specifies the owning office of the time series(s) whose data is to be included in the response. If this field is not specified, matching location level information from all offices shall be returned.
```

Example:
```
curl -X 'GET' \
  'http://localhost:11526/cwms-data/timeseries?name=ARBU.Elev.Inst.1Hour.0.Decodes-Raw&page-size=5000' \
  -H 'accept: application/json;version=2'
```

Resonse:
```

Error: response status is 404

Response body

Download{   "message": "Not found.",   "incidentIdentifier": "-741931119374001616",   "details": {} } 

Response headers connection:
 keep-alive  
content-length: 80  
content-type: application/json  
date: Mon,13 Jun 2022 17:02:21 GMT  
keep-alive: timeout=60 
 x-content-type-options: nosniff  
x-frame-options: SAMEORIGIN  
x-xss-protection: 1; mode=block
--

```

**Comment by adamkorynta** [comment]
Server-side monster stack trace:
```
WARNING: -7583446767271148142: Not found.
cwms.radar.api.NotFoundException: java.sql.SQLException: ORA-20025: LOCATION_ID_NOT_FOUND: The Location: "ARBU" does not exist.
ORA-06512: at "CWMS_20.CWMS_ERR", line 59
ORA-06512: at "CWMS_20.CWMS_LOC", line 128
ORA-01403: no data found
ORA-06512: at "CWMS_20.CWMS_LOC", line 115
ORA-01403: no data found
ORA-06512: at "CWMS_20.CWMS_LOC", line 91
ORA-06512: at "CWMS_20.CWMS_TS", line 11695
ORA-01403: no data found
ORA-06512: at "CWMS_20.CWMS_TS", line 11674
ORA-06512: at "CWMS_20.CWMS_TS", line 138
ORA-01403: no data found
ORA-06512: at "CWMS_20.CWMS_TS", line 126
ORA-06512: at "CWMS_20.CWMS_TS", line 41
ORA-06512: at "CWMS_20.CWMS_TS", line 26
ORA-06512: at "CWMS_20.CWMS_TS", line 11755

	at cwms.radar.data.dao.TimeSeriesDaoImpl.getTimeseries(TimeSeriesDaoImpl.java:290)
	at cwms.radar.data.dao.TimeSeriesDaoImpl.getTimeseries(TimeSeriesDaoImpl.java:117)
	at cwms.radar.api.TimeSeriesController.getAll(TimeSeriesController.java:266)
	at io.javalin.apibuilder.CrudFunction$1.invoke$lambda-0(CrudHandler.kt:30)
	at io.javalin.apibuilder.CrudFunctionHandler.handle(CrudHandler.kt)
	at cwms.radar.security.CwmsAccessManager.manage(CwmsAccessManager.java:45)
	at io.javalin.http.JavalinServlet.addHandler$lambda-5(JavalinServlet.kt:113)
	at io.javalin.http.JavalinServlet$service$tryBeforeAndEndpointHandlers$1.invoke(JavalinServlet.kt:44)
	at io.javalin.http.JavalinServlet$service$tryBeforeAndEndpointHandlers$1.invoke(JavalinServlet.kt:39)
	at io.javalin.http.JavalinServlet.service$tryWithExceptionMapper(JavalinServlet.kt:129)
	at io.javalin.http.JavalinServlet.service$tryBeforeAndEndpointHandlers(JavalinServlet.kt:39)
	at io.javalin.http.JavalinServlet.service(JavalinServlet.kt:87)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at cwms.radar.ApiServlet.service(ApiServlet.java:294)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:895)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1722)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: ORA-20025: LOCATION_ID_NOT_FOUND: The Location: "ARBU" does not exist.
ORA-06512: at "CWMS_20.CWMS_ERR", line 59
ORA-06512: at "CWMS_20.CWMS_LOC", line 128
ORA-01403: no data found
ORA-06512: at "CWMS_20.CWMS_LOC", line 115
ORA-01403: no data found
ORA-06512: at "CWMS_20.CWMS_LOC", line 91
ORA-06512: at "CWMS_20.CWMS_TS", line 11695
ORA-01403: no data found
ORA-06512: at "CWMS_20.CWMS_TS", line 11674
ORA-06512: at "CWMS_20.CWMS_TS", line 138
ORA-01403: no data found
ORA-06512: at "CWMS_20.CWMS_TS", line 126
ORA-06512: at "CWMS_20.CWMS_TS", line 41
ORA-06512: at "CWMS_20.CWMS_TS", line 26
ORA-06512: at "CWMS_20.CWMS_TS", line 11755

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:509)
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:461)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1104)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:550)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:268)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:655)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:270)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:91)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:807)
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:983)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1168)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3666)
	at oracle.jdbc.driver.T4CPreparedStatement.executeInternal(T4CPreparedStatement.java:1426)
	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3778)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1081)
	at sun.reflect.GeneratedMethodAccessor146.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:118)
	at com.sun.proxy.$Proxy9.execute(Unknown Source)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:209)
	at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:3416)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:268)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:350)
	at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:393)
	at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:380)
	at org.jooq.impl.AbstractResultQuery.fetchOne(AbstractResultQuery.java:545)
	at org.jooq.impl.AbstractResultQuery.fetchOne(AbstractResultQuery.java:550)
	at org.jooq.impl.SelectImpl.fetchOne(SelectImpl.java:2884)
	at cwms.radar.data.dao.TimeSeriesDaoImpl.getTimeseries(TimeSeriesDaoImpl.java:244)
	... 32 more
Caused by: Error : 20025, Position : 7, Sql = select "CWMS_20"."CWMS_TS"."GET_TS_ID"(:1 , "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"())) "NAME", "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"()) "OFFICE_ID", "CWMS_20"."CWMS_UTIL"."GET_DEFAULT_UNITS"("CWMS_20"."CWMS_TS"."GET_BASE_PARAMETER_ID"("CWMS_20"."CWMS_TS"."GET_TS_CODE"("CWMS_20"."CWMS_TS"."GET_TS_ID"(:2 , "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"())), "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"()))), :3 ) "UNITS", "CWMS_20"."CWMS_TS"."GET_INTERVAL"("CWMS_20"."CWMS_TS"."GET_TS_ID"(:4 , "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"()))) "INTERVAL", "CWMS_20"."CWMS_UTIL"."SPLIT_TEXT"("CWMS_20"."CWMS_TS"."GET_TS_ID"(:5 , "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"())), :6 , :7 , :8 ) "LOC_PART", upper("CWMS_20"."CWMS_UTIL"."SPLIT_TEXT"("CWMS_20"."CWMS_TS"."GET_TS_ID"(:9 , "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"())), :10 , :11 , :12 )) "PARM_PART", case upper("CWMS_20"."CWMS_UTIL"."SPLIT_TEXT"("CWMS_20"."CWMS_TS"."GET_TS_ID"(:13 , "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"())), :14 , :15 , :16 )) when :17  then "CWMS_20"."CWMS_LOC"."GET_VERTICAL_DATUM_INFO_F"("CWMS_20"."CWMS_UTIL"."SPLIT_TEXT"("CWMS_20"."CWMS_TS"."GET_TS_ID"(:18 , "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"())), :19 , :20 , :21 ), "CWMS_20"."CWMS_UTIL"."GET_DEFAULT_UNITS"("CWMS_20"."CWMS_TS"."GET_BASE_PARAMETER_ID"("CWMS_20"."CWMS_TS"."GET_TS_CODE"("CWMS_20"."CWMS_TS"."GET_TS_ID"(:22 , "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"())), "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"()))), :23 ), "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"())) else :24  end "VERTICAL_DATUM", (select count(*) from table("CWMS_20"."CWMS_TS"."RETRIEVE_TS_OUT_TAB"(
  "CWMS_20"."CWMS_TS"."GET_TS_ID"(
    'ARBU.Elev.Inst.1Hour.0.Ccp-Rev', 
    "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"())
  ), 
  "CWMS_20"."CWMS_UTIL"."GET_DEFAULT_UNITS"(
    "CWMS_20"."CWMS_TS"."GET_BASE_PARAMETER_ID"("CWMS_20"."CWMS_TS"."GET_TS_CODE"(
      "CWMS_20"."CWMS_TS"."GET_TS_ID"(
        'ARBU.Elev.Inst.1Hour.0.Ccp-Rev', 
        "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"())
      ), 
      "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"())
    )), 
    'SI'
  ), 
  "CWMS_20"."CWMS_UTIL"."TO_TIMESTAMP"(1523808000000), 
  "CWMS_20"."CWMS_UTIL"."TO_TIMESTAMP"(1524240000000), 
  'UTC', 
  null, 
  null, 
  null, 
  null, 
  null, 
  null, 
  null, 
  "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"())
))) "TOTAL", (select "CWMS_20"."AV_CWMS_TS_ID2"."INTERVAL_UTC_OFFSET" "INTERVAL_UTC_OFFSET" from "CWMS_20"."AV_CWMS_TS_ID2" where ("CWMS_20"."AV_CWMS_TS_ID2"."CWMS_TS_ID" = "CWMS_20"."CWMS_TS"."GET_TS_ID"(:25 , "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"())) and "CWMS_20"."AV_CWMS_TS_ID2"."ALIASED_ITEM" is null)), (select "CWMS_20"."AV_CWMS_TS_ID2"."TIME_ZONE_ID" from "CWMS_20"."AV_CWMS_TS_ID2" where ("CWMS_20"."AV_CWMS_TS_ID2"."CWMS_TS_ID" = "CWMS_20"."CWMS_TS"."GET_TS_ID"(:26 , "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"())) and "CWMS_20"."AV_CWMS_TS_ID2"."ALIASED_ITEM" is null)) "TIME_ZONE_ID" from dual, OriginalSql = select "CWMS_20"."CWMS_TS"."GET_TS_ID"(?, "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"())) "NAME", "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"()) "OFFICE_ID", "CWMS_20"."CWMS_UTIL"."GET_DEFAULT_UNITS"("CWMS_20"."CWMS_TS"."GET_BASE_PARAMETER_ID"("CWMS_20"."CWMS_TS"."GET_TS_CODE"("CWMS_20"."CWMS_TS"."GET_TS_ID"(?, "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"())), "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"()))), ?) "UNITS", "CWMS_20"."CWMS_TS"."GET_INTERVAL"("CWMS_20"."CWMS_TS"."GET_TS_ID"(?, "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"()))) "INTERVAL", "CWMS_20"."CWMS_UTIL"."SPLIT_TEXT"("CWMS_20"."CWMS_TS"."GET_TS_ID"(?, "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"())), ?, ?, ?) "LOC_PART", upper("CWMS_20"."CWMS_UTIL"."SPLIT_TEXT"("CWMS_20"."CWMS_TS"."GET_TS_ID"(?, "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"())), ?, ?, ?)) "PARM_PART", case upper("CWMS_20"."CWMS_UTIL"."SPLIT_TEXT"("CWMS_20"."CWMS_TS"."GET_TS_ID"(?, "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"())), ?, ?, ?)) when ? then "CWMS_20"."CWMS_LOC"."GET_VERTICAL_DATUM_INFO_F"("CWMS_20"."CWMS_UTIL"."SPLIT_TEXT"("CWMS_20"."CWMS_TS"."GET_TS_ID"(?, "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"())), ?, ?, ?), "CWMS_20"."CWMS_UTIL"."GET_DEFAULT_UNITS"("CWMS_20"."CWMS_TS"."GET_BASE_PARAMETER_ID"("CWMS_20"."CWMS_TS"."GET_TS_CODE"("CWMS_20"."CWMS_TS"."GET_TS_ID"(?, "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"())), "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"()))), ?), "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"())) else ? end "VERTICAL_DATUM", (select count(*) from table("CWMS_20"."CWMS_TS"."RETRIEVE_TS_OUT_TAB"(
  "CWMS_20"."CWMS_TS"."GET_TS_ID"(
    'ARBU.Elev.Inst.1Hour.0.Ccp-Rev', 
    "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"())
  ), 
  "CWMS_20"."CWMS_UTIL"."GET_DEFAULT_UNITS"(
    "CWMS_20"."CWMS_TS"."GET_BASE_PARAMETER_ID"("CWMS_20"."CWMS_TS"."GET_TS_CODE"(
      "CWMS_20"."CWMS_TS"."GET_TS_ID"(
        'ARBU.Elev.Inst.1Hour.0.Ccp-Rev', 
        "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"())
      ), 
      "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"())
    )), 
    'SI'
  ), 
  "CWMS_20"."CWMS_UTIL"."TO_TIMESTAMP"(1523808000000), 
  "CWMS_20"."CWMS_UTIL"."TO_TIMESTAMP"(1524240000000), 
  'UTC', 
  null, 
  null, 
  null, 
  null, 
  null, 
  null, 
  null, 
  "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"())
))) "TOTAL", (select "CWMS_20"."AV_CWMS_TS_ID2"."INTERVAL_UTC_OFFSET" "INTERVAL_UTC_OFFSET" from "CWMS_20"."AV_CWMS_TS_ID2" where ("CWMS_20"."AV_CWMS_TS_ID2"."CWMS_TS_ID" = "CWMS_20"."CWMS_TS"."GET_TS_ID"(?, "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"())) and "CWMS_20"."AV_CWMS_TS_ID2"."ALIASED_ITEM" is null)), (select "CWMS_20"."AV_CWMS_TS_ID2"."TIME_ZONE_ID" from "CWMS_20"."AV_CWMS_TS_ID2" where ("CWMS_20"."AV_CWMS_TS_ID2"."CWMS_TS_ID" = "CWMS_20"."CWMS_TS"."GET_TS_ID"(?, "CWMS_20"."CWMS_UTIL"."GET_DB_OFFICE_ID"("CWMS_20"."CWMS_UTIL"."USER_OFFICE_ID"())) and "CWMS_20"."AV_CWMS_TS_ID2"."ALIASED_ITEM" is null)) "TIME_ZONE_ID" from dual, Error Msg = ORA-20025: LOCATION_ID_NOT_FOUND: The Location: "ARBU" does not exist.
ORA-06512: at "CWMS_20.CWMS_ERR", line 59
ORA-06512: at "CWMS_20.CWMS_LOC", line 128
ORA-01403: no data found
ORA-06512: at "CWMS_20.CWMS_LOC", line 115
ORA-01403: no data found
ORA-06512: at "CWMS_20.CWMS_LOC", line 91
ORA-06512: at "CWMS_20.CWMS_TS", line 11695
ORA-01403: no data found
ORA-06512: at "CWMS_20.CWMS_TS", line 11674
ORA-06512: at "CWMS_20.CWMS_TS", line 138
ORA-01403: no data found
ORA-06512: at "CWMS_20.CWMS_TS", line 126
ORA-06512: at "CWMS_20.CWMS_TS", line 41
ORA-06512: at "CWMS_20.CWMS_TS", line 26
ORA-06512: at "CWMS_20.CWMS_TS", line 11755

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:513)
	... 61 more

```

**Comment by rma-rripken** [comment]
I just tried this and it did not throw an exception for me.  This must have been fixed somewhere along the way.
