### ISSUE TITLE
Error code 500 when attempting to view records through USACE RADAR

### ISSUE THREAD

**Issue by KevinSmith-RMA** [USACE/cwms-data-api#193]
When trying to access records through CWMS v3.3 Beta 27 Data Status Summary, the Error code 500 below is returned.

These are records that were used on WebEx with HEC on Thursday  7/21/2022 to demonstrate an exceoption for records with veritical datum of OTHER. When trying to replicate the issue using those records, the error below is instead returned.

```
Jul 25, 2022 5:13:50 PM hec.dataui.tx.awt.DisplayOracleTS handleError
WARNING: Error while retrieving time series:
   -->Description: Arkport.Elev.Inst.15Minutes.0.DCP-rev;
   -->Start Time: Tue Jul 5 01:13:00 UTC 2022;
   -->End Time:   Tue Jul 26 01:13:00 UTC 2022;
   -->Interval Offset from sun.util.calendar.ZoneInfo[id="UTC",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null]: UNDEFINED;
   -->Units: undef;
   -->Preserve: true;
   -->MaxTimeGap: 0 Mins  or  0 Hours
At URL: https://cwms-data.usace.army.mil/cwms-data/
java.util.concurrent.CompletionException: hec.db.DbRuntimeException: hec.db.DbIoException: java.io.IOException: Unknown error occurred for request: Request{method=GET, url=https://cwms-data.usace.army.mil/cwms-data/timeseries?unit=SI&timezone=UTC&name=Arkport.Elev.Inst.15Minutes.0.DCP-rev&pageSize=5000&end=2022-07-26T01%3A13%3A00Z&office=NAB&begin=2022-07-05T01%3A13%3A00Z, headers=[accept:application/json;version=2]}
 Error code: 500
{"message":"System Error","incidentIdentifier":"-4510078843291253028","details":{}}
        at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
        at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: hec.db.DbRuntimeException: hec.db.DbIoException: java.io.IOException: Unknown error occurred for request: Request{method=GET, url=https://cwms-data.usace.army.mil/cwms-data/timeseries?unit=SI&timezone=UTC&name=Arkport.Elev.Inst.15Minutes.0.DCP-rev&pageSize=5000&end=2022-07-26T01%3A13%3A00Z&office=NAB&begin=2022-07-05T01%3A13%3A00Z, headers=[accept:application/json;version=2]}
 Error code: 500
{"message":"System Error","incidentIdentifier":"-4510078843291253028","details":{}}
        at wcds.dbi.cwms.radar.CwmsTimeSeriesRadarDao.lambda$submitRetrieveTimeSeries$2(CwmsTimeSeriesRadarDao.java:341)
        ... 4 more
Caused by: hec.db.DbIoException: java.io.IOException: Unknown error occurred for request: Request{method=GET, url=https://cwms-data.usace.army.mil/cwms-data/timeseries?unit=SI&timezone=UTC&name=Arkport.Elev.Inst.15Minutes.0.DCP-rev&pageSize=5000&end=2022-07-26T01%3A13%3A00Z&office=NAB&begin=2022-07-05T01%3A13%3A00Z, headers=[accept:application/json;version=2]}
 Error code: 500
{"message":"System Error","incidentIdentifier":"-4510078843291253028","details":{}}
        at wcds.dbi.cwms.radar.CwmsDaoImpl.wrapIOException(CwmsDaoImpl.java:50)
        at wcds.dbi.cwms.radar.CwmsTimeSeriesRadarDao.retrieveTimeSeries(CwmsTimeSeriesRadarDao.java:199)
        at wcds.dbi.cwms.radar.CwmsTimeSeriesRadarDao.lambda$submitRetrieveTimeSeries$2(CwmsTimeSeriesRadarDao.java:337)
        ... 4 more
Caused by: java.io.IOException: Unknown error occurred for request: Request{method=GET, url=https://cwms-data.usace.army.mil/cwms-data/timeseries?unit=SI&timezone=UTC&name=Arkport.Elev.Inst.15Minutes.0.DCP-rev&pageSize=5000&end=2022-07-26T01%3A13%3A00Z&office=NAB&begin=2022-07-05T01%3A13%3A00Z, headers=[accept:application/json;version=2]}
 Error code: 500
{"message":"System Error","incidentIdentifier":"-4510078843291253028","details":{}}
        at mil.army.usace.hec.cwms.http.client.HttpRequestBuilderImpl$HttpRequestExecutorImpl.checkError(HttpRequestBuilderImpl.java:251)
        at mil.army.usace.hec.cwms.http.client.HttpRequestBuilderImpl$HttpRequestExecutorImpl.handleExecutionError(HttpRequestBuilderImpl.java:232)
        at mil.army.usace.hec.cwms.http.client.HttpRequestBuilderImpl$HttpRequestExecutorImpl.execute(HttpRequestBuilderImpl.java:222)
        at mil.army.usace.hec.cwms.radar.client.controllers.TimeSeriesController.retrieveTimeSeries(TimeSeriesController.java:48)
        at wcds.dbi.cwms.radar.CwmsTimeSeriesRadarDao.retrieveTimeSeries(CwmsTimeSeriesRadarDao.java:160)
        ... 5 more
```

**Comment by KevinSmith-RMA** [comment]
[DataStatus_error_code_500.log](https://github.com/USACE/cwms-radar-api/files/9191086/DataStatus_error_code_500.log)

Full log attached for reference.

**Comment by KevinSmith-RMA** [comment]
Note I am also seeing this error returned when trying to view CWMS RADAR data from the national URL through CAVI Time Series Icons.

**Comment by MikeNeilson** [comment]
At present the solution is to ask for less data at once. I've put int a request for a config tweak but it's at the database level not something we can easily fix in code. (short of giving direct access to the tables and recreating all the infrastructure.)
