### ISSUE TITLE
NullPointerException on levels getAll endpoint

### ISSUE THREAD

**Issue by adamkorynta** [USACE/cwms-data-api#209]
example cURL

```
curl -X 'GET' \
  'http://leary.rmanet.com:11526/cwms-data/levels?level-id-mask=%2A&page-size=400' \
  -H 'accept: application/json;version=2'
```

Received
```
{
  "message": "System Error",
  "incidentIdentifier": "-1195564157289992270",
  "details": {}
}
```

Server-side stack trace

```
Aug 24, 2022 4:38:30 AM cwms.radar.ApiServlet lambda$init$12
WARNING: error on request[-1195564157289992270]: /cwms-data/levels
java.lang.NullPointerException
	at cwms.radar.data.dto.LocationLevel$Builder.<init>(LocationLevel.java:297)
	at cwms.radar.data.dao.LocationLevelsDaoImpl.toLocationLevel(LocationLevelsDaoImpl.java:347)
	at cwms.radar.data.dao.LocationLevelsDaoImpl.lambda$getLocationLevels$4(LocationLevelsDaoImpl.java:283)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at cwms.radar.data.dao.LocationLevelsDaoImpl.getLocationLevels(LocationLevelsDaoImpl.java:283)
	at cwms.radar.api.LevelsController.getAll(LevelsController.java:271)
	at io.javalin.apibuilder.CrudFunction$1.invoke$lambda-0(CrudHandler.kt:30)
	at io.javalin.apibuilder.CrudFunctionHandler.handle(CrudHandler.kt)
	at cwms.radar.security.CwmsAccessManager.manage(CwmsAccessManager.java:45)
	at io.javalin.http.JavalinServlet.addHandler$lambda-0(JavalinServlet.kt:96)
	at io.javalin.http.JavalinServlet$lifecycle$2$1$1.invoke(JavalinServlet.kt:43)
	at io.javalin.http.JavalinServlet$lifecycle$2$1$1.invoke(JavalinServlet.kt:43)
	at io.javalin.http.JavalinServletHandler.executeNextTask(JavalinServletHandler.kt:98)
	at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$lambda-1(JavalinServletHandler.kt:85)
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:995)
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2137)
	at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$javalin(JavalinServletHandler.kt:85)
	at io.javalin.http.JavalinServletHandler.executeNextTask$lambda-10$lambda-9(JavalinServletHandler.kt:112)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616)
	at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:628)
	at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1996)
	at io.javalin.http.JavalinServletHandler.executeNextTask(JavalinServletHandler.kt:112)
	at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$lambda-1(JavalinServletHandler.kt:85)
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:995)
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2137)
	at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$javalin(JavalinServletHandler.kt:85)
	at io.javalin.http.JavalinServlet.service(JavalinServlet.kt:89)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at cwms.radar.ApiServlet.service(ApiServlet.java:332)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1787)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by adamkorynta** [comment]
I added a null check and then received:

```
SEVERE: Exception occurred while servicing http-request
java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: com/google/common/flogger/FluentLogger
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1005)
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2137)
	at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$javalin(JavalinServletHandler.kt:85)
	at io.javalin.http.JavalinServletHandler.executeNextTask$lambda-10$lambda-9(JavalinServletHandler.kt:112)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616)
	at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:628)
	at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1996)
	at io.javalin.http.JavalinServletHandler.executeNextTask(JavalinServletHandler.kt:112)
	at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$lambda-1(JavalinServletHandler.kt:85)
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:995)
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2137)
	at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$javalin(JavalinServletHandler.kt:85)
	at io.javalin.http.JavalinServlet.service(JavalinServlet.kt:89)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at cwms.radar.ApiServlet.service(ApiServlet.java:332)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1787)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.NoClassDefFoundError: com/google/common/flogger/FluentLogger
	at rma.util.RMAIO.<clinit>(RMAIO.java:42)
	at hec.data.level.JDomSeasonalIntervalImpl.setDaysHoursMinutesString(JDomSeasonalIntervalImpl.java:289)
	at cwms.radar.data.dao.LocationLevelsDaoImpl.parseSeasonalValues(LocationLevelsDaoImpl.java:396)
	at cwms.radar.data.dao.LocationLevelsDaoImpl.toLocationLevel(LocationLevelsDaoImpl.java:345)
	at cwms.radar.data.dao.LocationLevelsDaoImpl.lambda$getLocationLevels$4(LocationLevelsDaoImpl.java:283)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at cwms.radar.data.dao.LocationLevelsDaoImpl.getLocationLevels(LocationLevelsDaoImpl.java:283)
	at cwms.radar.api.LevelsController.getAll(LevelsController.java:271)
	at io.javalin.apibuilder.CrudFunction$1.invoke$lambda-0(CrudHandler.kt:30)
	at io.javalin.apibuilder.CrudFunctionHandler.handle(CrudHandler.kt)
	at cwms.radar.security.CwmsAccessManager.manage(CwmsAccessManager.java:45)
	at io.javalin.http.JavalinServlet.addHandler$lambda-0(JavalinServlet.kt:96)
	at io.javalin.http.JavalinServlet$lifecycle$2$1$1.invoke(JavalinServlet.kt:43)
	at io.javalin.http.JavalinServlet$lifecycle$2$1$1.invoke(JavalinServlet.kt:43)
	at io.javalin.http.JavalinServletHandler.executeNextTask(JavalinServletHandler.kt:98)
	at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$lambda-1(JavalinServletHandler.kt:85)
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:995)
	... 33 more
Caused by: java.lang.ClassNotFoundException: com.google.common.flogger.FluentLogger
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1412)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1220)
	... 57 more
```

**Comment by rma-rripken** [comment]
Looks like this is happening b/c for some reason we decided to exclude the transitive dependencies coming from bringing in monolith.

**Comment by rma-rripken** [comment]
I think #208 will fix this
