### ISSUE TITLE
NullPointerException on levels getOne

### ISSUE THREAD

**Issue by adamkorynta** [USACE/cwms-data-api#211]
Example cURL:

```
curl -X 'GET' \
  'http://leary.rmanet.com:11526/cwms-data/levels/Barren.Elev.Inst.0.Bottom%20of%20Inlet?office=LRL&effective-date=1900-01-01T06%3A00%3A00Z' \
  -H 'accept: application/json;version=2'
```

Response
```
{
  "message": "Failed to retrieve Location Level request: Failed to retrieve Location Level",
  "incidentIdentifier": "3703751948246940770",
  "details": {}
}
```

Server-side stack trace:

```
SEVERE: 3703751948246940770: Failed to retrieve Location Level request: Failed to retrieve Location Level
java.lang.RuntimeException: Failed to retrieve Location Level
	at cwms.radar.data.dao.LocationLevelsDaoImpl.retrieveLocationLevel(LocationLevelsDaoImpl.java:191)
	at cwms.radar.api.LevelsController.getOne(LevelsController.java:355)
	at io.javalin.apibuilder.CrudFunction$2.invoke$lambda-0(CrudHandler.kt:31)
	at io.javalin.apibuilder.CrudFunctionHandler.handle(CrudHandler.kt)
	at cwms.radar.security.CwmsAccessManager.manage(CwmsAccessManager.java:45)
	at io.javalin.http.JavalinServlet.addHandler$lambda-0(JavalinServlet.kt:96)
	at io.javalin.http.JavalinServlet$lifecycle$2$1$1.invoke(JavalinServlet.kt:43)
	at io.javalin.http.JavalinServlet$lifecycle$2$1$1.invoke(JavalinServlet.kt:43)
	at io.javalin.http.JavalinServletHandler.executeNextTask(JavalinServletHandler.kt:98)
	at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$lambda-1(JavalinServletHandler.kt:85)
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:995)
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2137)
	at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$javalin(JavalinServletHandler.kt:85)
	at io.javalin.http.JavalinServletHandler.executeNextTask$lambda-10$lambda-9(JavalinServletHandler.kt:112)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616)
	at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:628)
	at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1996)
	at io.javalin.http.JavalinServletHandler.executeNextTask(JavalinServletHandler.kt:112)
	at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$lambda-1(JavalinServletHandler.kt:85)
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:995)
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2137)
	at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$javalin(JavalinServletHandler.kt:85)
	at io.javalin.http.JavalinServlet.service(JavalinServlet.kt:89)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at cwms.radar.ApiServlet.service(ApiServlet.java:332)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1787)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
Caused by: org.jooq.exception.DataAccessException: Error while running ConnectionCallable
	at org.jooq.impl.DefaultDSLContext.connectionResult(DefaultDSLContext.java:634)
	at org.jooq.impl.DefaultDSLContext.connection(DefaultDSLContext.java:643)
	at cwms.radar.data.dao.LocationLevelsDaoImpl.retrieveLocationLevel(LocationLevelsDaoImpl.java:181)
	... 43 more
Caused by: java.lang.NullPointerException
	at cwms.radar.data.dao.LocationLevelsDaoImpl.getLevelFromPojo(LocationLevelsDaoImpl.java:201)
	at cwms.radar.data.dao.LocationLevelsDaoImpl.lambda$retrieveLocationLevel$3(LocationLevelsDaoImpl.java:187)
	at org.jooq.impl.DefaultDSLContext$4.run(DefaultDSLContext.java:646)
	at org.jooq.impl.DefaultDSLContext$4.run(DefaultDSLContext.java:643)
	at org.jooq.impl.DefaultDSLContext.connectionResult(DefaultDSLContext.java:631)
	... 45 more
```

**Comment by rma-rripken** [comment]
I believe PR #208 will add the needed null check.
