### ISSUE TITLE
NullPointerException on locations/getOne endpoint when no time zone

### ISSUE THREAD

**Issue by adamkorynta** [USACE/cwms-data-api#219]
This issue occurs if the location has a null time zone.

Server-side stack trace:
```
WARNING: error on request[4245059605031346117]: /cwms-data/locations/Adamsboro
java.lang.NullPointerException: zoneId
	at java.util.Objects.requireNonNull(Objects.java:228)
	at java.time.ZoneId.of(ZoneId.java:403)
	at java.time.ZoneId.of(ZoneId.java:359)
	at cwms.radar.data.dao.LocationsDaoImpl.buildLocation(LocationsDaoImpl.java:81)
	at cwms.radar.data.dao.LocationsDaoImpl.getLocation(LocationsDaoImpl.java:73)
	at cwms.radar.api.LocationController.getOne(LocationController.java:223)
	at io.javalin.apibuilder.CrudFunction$2.invoke$lambda-0(CrudHandler.kt:31)
	at io.javalin.apibuilder.CrudFunctionHandler.handle(CrudHandler.kt)
	at cwms.radar.security.CwmsAccessManager.manage(CwmsAccessManager.java:45)
	at io.javalin.http.JavalinServlet.addHandler$lambda-0(JavalinServlet.kt:96)
	at io.javalin.http.JavalinServlet$lifecycle$2$1$1.invoke(JavalinServlet.kt:43)
	at io.javalin.http.JavalinServlet$lifecycle$2$1$1.invoke(JavalinServlet.kt:43)
	at io.javalin.http.JavalinServletHandler.executeNextTask(JavalinServletHandler.kt:98)
	at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$lambda-1(JavalinServletHandler.kt:85)
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:995)
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2137)
	at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$javalin(JavalinServletHandler.kt:85)
	at io.javalin.http.JavalinServletHandler.executeNextTask$lambda-10$lambda-9(JavalinServletHandler.kt:112)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616)
	at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:628)
	at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1996)
	at io.javalin.http.JavalinServletHandler.executeNextTask(JavalinServletHandler.kt:112)
	at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$lambda-1(JavalinServletHandler.kt:85)
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:995)
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2137)
	at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$javalin(JavalinServletHandler.kt:85)
	at io.javalin.http.JavalinServlet.service(JavalinServlet.kt:89)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at cwms.radar.ApiServlet.service(ApiServlet.java:332)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1787)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by adamkorynta** [comment]
I believe this is also causing issues when calling the getOne for ratings/


```
Sep 27, 2022 10:57:48 PM org.apache.catalina.authenticator.AuthenticatorBase invoke
FINE: Security checking request GET /cwms-data/ratings/Adamsboro.Stage;Flow.BASE.PRODUCTION
Sep 27, 2022 10:57:48 PM org.apache.catalina.realm.RealmBase findSecurityConstraints
FINE:   Checking constraint 'SecurityConstraint[CWMS DATA]' against GET /ratings/Adamsboro.Stage --> false
Sep 27, 2022 10:57:48 PM org.apache.catalina.realm.RealmBase findSecurityConstraints
FINE:   Checking constraint 'SecurityConstraint[CWMS DATA]' against GET /ratings/Adamsboro.Stage --> false
Sep 27, 2022 10:57:48 PM org.apache.catalina.realm.RealmBase findSecurityConstraints
FINE:   Checking constraint 'SecurityConstraint[CWMS DATA]' against GET /ratings/Adamsboro.Stage --> false
Sep 27, 2022 10:57:48 PM org.apache.catalina.realm.RealmBase findSecurityConstraints
FINE:   Checking constraint 'SecurityConstraint[CWMS DATA]' against GET /ratings/Adamsboro.Stage --> false
Sep 27, 2022 10:57:48 PM org.apache.catalina.realm.RealmBase findSecurityConstraints
FINE:   No applicable constraint located
Sep 27, 2022 10:57:48 PM org.apache.catalina.authenticator.AuthenticatorBase invoke
FINE: Not subject to any constraint
Sep 27, 2022 10:57:49 PM org.apache.catalina.authenticator.AuthenticatorBase invoke
FINE: Security checking request GET /cwms-data/locations/Adamsboro
Sep 27, 2022 10:57:49 PM org.apache.catalina.realm.RealmBase findSecurityConstraints
FINE:   Checking constraint 'SecurityConstraint[CWMS DATA]' against GET /locations/Adamsboro --> false
Sep 27, 2022 10:57:49 PM org.apache.catalina.realm.RealmBase findSecurityConstraints
FINE:   Checking constraint 'SecurityConstraint[CWMS DATA]' against GET /locations/Adamsboro --> false
Sep 27, 2022 10:57:49 PM org.apache.catalina.realm.RealmBase findSecurityConstraints
FINE:   Checking constraint 'SecurityConstraint[CWMS DATA]' against GET /locations/Adamsboro --> false
Sep 27, 2022 10:57:49 PM org.apache.catalina.realm.RealmBase findSecurityConstraints
FINE:   Checking constraint 'SecurityConstraint[CWMS DATA]' against GET /locations/Adamsboro --> false
Sep 27, 2022 10:57:49 PM org.apache.catalina.realm.RealmBase findSecurityConstraints
FINE:   No applicable constraint located
Sep 27, 2022 10:57:49 PM org.apache.catalina.authenticator.AuthenticatorBase invoke
FINE: Not subject to any constraint
Sep 27, 2022 10:57:49 PM cwms.radar.ApiServlet lambda$init$10
WARNING: error on request[-2463317098378324965]: /cwms-data/locations/Adamsboro [ERROR: UNUSED LOG ARGUMENTS]

```

**Comment by rma-rripken** [comment]
The  UNUSED LOG ARGUMENTS part is b/c I didn't fix a logger usage when I did some search and replace.   The NPE in the location dao should be an easy fix.    I'm not sure what the underlying error is in the rating getOne that caused the UNUSED LOG ARGUMENTS to show up.  Might need to follow up one the other two issues are fixed
