### ISSUE TITLE
Add endpoints for TS identifier CRUD operatations

### ISSUE THREAD

**Issue by adamkorynta** [USACE/cwms-data-api#286]
These are used by CWMS client API's.

**Comment by adamkorynta** [comment]
Rename is kinda provided through the ts catalog retrieval unless there's other metadata that would be nice or relevant to add in.

**Comment by adamkorynta** [comment]
rename and updating the interval offset is specifically used by CWMSVue

**Comment by adamkorynta** [comment]
Tried out the getOne endpoint through swagger but received an error code 501. There are no other accept header types available in swagger.

```
curl -X 'GET' \
  'https://leary:8443/cwms-data/timeseries/identifier-descriptor/ALTU.Precip-Cuml.Inst.1Hour.0.Decodes-Raw?office=SWT' \
  -H 'accept: application/json;version=2'
```
Response:
```
{
  "message": "Formatting error:No Format for this content-type and data-type : (application/json;version=2, cwms.radar.data.dto.TimeSeriesIdentifierDescriptor)",
  "incidentIdentifier": "5591629106169778975",
  "details": {}
}
```

Server-side stack trace:
```
06-Mar-2023 23:54:42.878 SEVERE [https-jsse-nio-8443-exec-18] cwms.radar.ApiServlet.lambda$init$3 5591629106169778975: Formatting error:No Format for this content-type and data-type : (application/json;version=2, cwms.radar.data.dto.TimeSeriesIdentifierDescriptor) for request: https://leary:8443/cwms-data/timeseries/identifier-descriptor/ALTU.Precip-Cuml.Inst.1Hour.0.Decodes-Raw?office=SWT
	cwms.radar.formatters.FormattingException: No Format for this content-type and data-type : (application/json;version=2, cwms.radar.data.dto.TimeSeriesIdentifierDescriptor)
		at cwms.radar.formatters.Formats.getFormatted(Formats.java:122)
		at cwms.radar.formatters.Formats.format(Formats.java:167)
		at cwms.radar.api.TimeSeriesIdentifierDescriptorController.getOne(TimeSeriesIdentifierDescriptorController.java:167)
		at io.javalin.apibuilder.CrudFunction$2.invoke$lambda-0(CrudHandler.kt:31)
		at io.javalin.apibuilder.CrudFunctionHandler.handle(CrudHandler.kt)
		at cwms.radar.security.CwmsAccessManager.manage(CwmsAccessManager.java:43)
		at io.javalin.http.JavalinServlet.addHandler$lambda-0(JavalinServlet.kt:96)
		at io.javalin.http.JavalinServlet$lifecycle$2$1$1.invoke(JavalinServlet.kt:43)
		at io.javalin.http.JavalinServlet$lifecycle$2$1$1.invoke(JavalinServlet.kt:43)
		at io.javalin.http.JavalinServletHandler.executeNextTask(JavalinServletHandler.kt:99)
		at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$lambda-1(JavalinServletHandler.kt:85)
		at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:995)
		at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2137)
		at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$javalin(JavalinServletHandler.kt:85)
		at io.javalin.http.JavalinServletHandler.executeNextTask$lambda-11$lambda-10(JavalinServletHandler.kt:119)
		at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616)
		at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:628)
		at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1996)
		at io.javalin.http.JavalinServletHandler.executeNextTask(JavalinServletHandler.kt:119)
		at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$lambda-1(JavalinServletHandler.kt:85)
		at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:995)
		at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2137)
		at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$javalin(JavalinServletHandler.kt:85)
		at io.javalin.http.JavalinServlet.service(JavalinServlet.kt:89)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:779)
		at cwms.radar.ApiServlet.service(ApiServlet.java:414)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:779)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:357)
		at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:176)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:660)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
		at org.apache.catalina.authenticator.SingleSignOn.invoke(SingleSignOn.java:261)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1789)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.lang.Thread.run(Thread.java:750)
```

**Comment by adamkorynta** [comment]
The getAll endpoint returns the same error.

**Comment by adamkorynta** [comment]
Additionally, the swagger docs for the `TimeSeriesIdentifierDescriptor` include a full separate implementation of `ZoneId` with rules and offsets, etc. It should probably be serialized/deserialized as a `String` type instead of an `Object` type.

```
    TimeSeriesIdentifierDescriptor:
      type: object
      properties:
        office-id:
          type: string
        time-series-id:
          type: string
        zone-id:
          type: object
          properties:
            rules:
              type: object
              properties:
                transitions:
                  type: array
                  items:
                    type: object
                    properties:
                      offsetBefore:
                        type: object
                        properties:
                          totalSeconds:
                            type: integer
                            format: int32
                          id:
                            type: string
                      offsetAfter:
                        type: object
                        properties:
                          totalSeconds:
                            type: integer
                            format: int32
                          id:
                            type: string
                      overlap:
                        type: boolean
                      instant:
                        type: string
                        format: date-time
                      duration:
                        type: object
                        properties:
                          seconds:
                            type: integer
                            format: int64
                          nano:
                            type: integer
                            format: int32
                          zero:
                            type: boolean
                          negative:
                            type: boolean
                          units:
                            type: array
                            items:
                              type: object
                              properties:
                                durationEstimated:
                                  type: boolean
                                dateBased:
                                  type: boolean
                                timeBased:
                                  type: boolean
                      dateTimeBefore:
                        type: string
                        format: date-time
                      gap:
                        type: boolean
                      dateTimeAfter:
                        type: string
                        format: date-time
                transitionRules:
                  type: array
                  items:
                    type: object
                    properties:
                      month:
                        type: string
                        enum:
                          - JANUARY
                          - FEBRUARY
                          - MARCH
                          - APRIL
                          - MAY
                          - JUNE
                          - JULY
                          - AUGUST
                          - SEPTEMBER
                          - OCTOBER
                          - NOVEMBER
                          - DECEMBER
                      timeDefinition:
                        type: string
                        enum:
                          - UTC
                          - WALL
                          - STANDARD
                      standardOffset:
                        type: object
                        properties:
                          totalSeconds:
                            type: integer
                            format: int32
                          id:
                            type: string
                      offsetBefore:
                        type: object
                        properties:
                          totalSeconds:
                            type: integer
                            format: int32
                          id:
                            type: string
                      offsetAfter:
                        type: object
                        properties:
                          totalSeconds:
                            type: integer
                            format: int32
                          id:
                            type: string
                      dayOfWeek:
                        type: string
                        enum:
                          - MONDAY
                          - TUESDAY
                          - WEDNESDAY
                          - THURSDAY
                          - FRIDAY
                          - SATURDAY
                          - SUNDAY
                      dayOfMonthIndicator:
                        type: integer
                        format: int32
                      localTime:
                        $ref: '#/components/schemas/LocalTime'
                      midnightEndOfDay:
                        type: boolean
                fixedOffset:
                  type: boolean
            id:
              type: string
        interval-offset-minutes:
          type: integer
          format: int64
        active:
          type: boolean
```

**Comment by adamkorynta** [comment]
If I run a cURL without the accept header, I get this on the getAll:

```
07-Mar-2023 16:28:00.955 WARNING [https-jsse-nio-8443-exec-31] cwms.radar.ApiServlet.lambda$init$10 error on request[-6837253075772637808]: /cwms-data/timeseries/identifier-descriptor
	java.lang.StringIndexOutOfBoundsException: String index out of range: -1
		at java.lang.String.substring(String.java:1967)
		at cwms.radar.data.dao.TimeSeriesIdentifierDescriptorDao.toDescriptor(TimeSeriesIdentifierDescriptorDao.java:76)
		at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
		at java.util.Iterator.forEachRemaining(Iterator.java:116)
		at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
		at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
		at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
		at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
		at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
		at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
		at cwms.radar.data.dao.TimeSeriesIdentifierDescriptorDao.getTimeSeriesIdentifiers(TimeSeriesIdentifierDescriptorDao.java:66)
		at cwms.radar.api.TimeSeriesIdentifierDescriptorController.getAll(TimeSeriesIdentifierDescriptorController.java:116)
		at io.javalin.apibuilder.CrudFunction$1.invoke$lambda-0(CrudHandler.kt:30)
		at io.javalin.apibuilder.CrudFunctionHandler.handle(CrudHandler.kt)
		at cwms.radar.security.CwmsAccessManager.manage(CwmsAccessManager.java:43)
		at io.javalin.http.JavalinServlet.addHandler$lambda-0(JavalinServlet.kt:96)
		at io.javalin.http.JavalinServlet$lifecycle$2$1$1.invoke(JavalinServlet.kt:43)
		at io.javalin.http.JavalinServlet$lifecycle$2$1$1.invoke(JavalinServlet.kt:43)
		at io.javalin.http.JavalinServletHandler.executeNextTask(JavalinServletHandler.kt:99)
		at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$lambda-1(JavalinServletHandler.kt:85)
		at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:995)
		at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2137)
		at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$javalin(JavalinServletHandler.kt:85)
		at io.javalin.http.JavalinServletHandler.executeNextTask$lambda-11$lambda-10(JavalinServletHandler.kt:119)
		at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616)
		at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:628)
		at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1996)
		at io.javalin.http.JavalinServletHandler.executeNextTask(JavalinServletHandler.kt:119)
		at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$lambda-1(JavalinServletHandler.kt:85)
		at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:995)
		at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2137)
		at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$javalin(JavalinServletHandler.kt:85)
		at io.javalin.http.JavalinServlet.service(JavalinServlet.kt:89)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:779)
		at cwms.radar.ApiServlet.service(ApiServlet.java:414)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:779)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:357)
		at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:176)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:660)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
		at org.apache.catalina.authenticator.SingleSignOn.invoke(SingleSignOn.java:261)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1789)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.lang.Thread.run(Thread.java:750)
```

**Comment by adamkorynta** [comment]
And the getOne requires that I set the accept content-type

```
07-Mar-2023 16:31:06.359 SEVERE [https-jsse-nio-8443-exec-22] cwms.radar.ApiServlet.lambda$init$3 1011141246176996094: Formatting error:No Format for this content-type and data-type : (application/json, cwms.radar.data.dto.TimeSeriesIdentifierDescriptor) for request: https://leary:8443/cwms-data/timeseries/identifier-descriptor/ALTU.Elev.Inst.15Minutes.0.Decodes-Raw?office=SWT
	cwms.radar.formatters.FormattingException: No Format for this content-type and data-type : (application/json, cwms.radar.data.dto.TimeSeriesIdentifierDescriptor)
		at cwms.radar.formatters.Formats.getFormatted(Formats.java:122)
		at cwms.radar.formatters.Formats.format(Formats.java:167)
		at cwms.radar.api.TimeSeriesIdentifierDescriptorController.getOne(TimeSeriesIdentifierDescriptorController.java:167)
		at io.javalin.apibuilder.CrudFunction$2.invoke$lambda-0(CrudHandler.kt:31)
		at io.javalin.apibuilder.CrudFunctionHandler.handle(CrudHandler.kt)
		at cwms.radar.security.CwmsAccessManager.manage(CwmsAccessManager.java:43)
		at io.javalin.http.JavalinServlet.addHandler$lambda-0(JavalinServlet.kt:96)
		at io.javalin.http.JavalinServlet$lifecycle$2$1$1.invoke(JavalinServlet.kt:43)
		at io.javalin.http.JavalinServlet$lifecycle$2$1$1.invoke(JavalinServlet.kt:43)
		at io.javalin.http.JavalinServletHandler.executeNextTask(JavalinServletHandler.kt:99)
		at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$lambda-1(JavalinServletHandler.kt:85)
		at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:995)
		at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2137)
		at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$javalin(JavalinServletHandler.kt:85)
		at io.javalin.http.JavalinServletHandler.executeNextTask$lambda-11$lambda-10(JavalinServletHandler.kt:119)
		at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616)
		at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:628)
		at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1996)
		at io.javalin.http.JavalinServletHandler.executeNextTask(JavalinServletHandler.kt:119)
		at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$lambda-1(JavalinServletHandler.kt:85)
		at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:995)
		at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2137)
		at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$javalin(JavalinServletHandler.kt:85)
		at io.javalin.http.JavalinServlet.service(JavalinServlet.kt:89)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:779)
		at cwms.radar.ApiServlet.service(ApiServlet.java:414)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:779)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:357)
		at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:176)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:660)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
		at org.apache.catalina.authenticator.SingleSignOn.invoke(SingleSignOn.java:261)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1789)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.lang.Thread.run(Thread.java:750)

```

**Comment by rma-rripken** [comment]
The getOne currently calls into CwmsDbTsJooq retrieveTSIdentifierWithAliasSupport.   How important is that alias support?    I ask b/c getAll should probably behave the same way as the getOne or be documented to work differently.

**Comment by adamkorynta** [comment]
That is the only distinction between querying the ts catalog for the same information so it is vital. I'd prefer to remove the getAll endpoint since it isn't needed at this time.

**Comment by adamkorynta** [comment]
The patch endpoint should rename the `utc-offset` parameter to `interval-offset`. For local regular time series, this offset is relative to the location's time zone (and negative).

**Comment by adamkorynta** [comment]
The offset parameter should be typed as a number instead of a String.  
The `active` parameter should be typed as a boolean.
The snap forward/back should also be typed as numbers.

**Comment by adamkorynta** [comment]
Update doesn't work when only updating the interval offset.

**Comment by MikeNeilson** [comment]
is that correct behavior though? should we be able to update the interval offset if it's not null?... well, that answer my question partly there didn't it.

**Comment by adamkorynta** [comment]
Yes, as long as the data still works on the interval offset we should be able to update it (or like you said, update it if undefined). We use that in our converter from PRTS to LRTS when the data was already correctly on the LRTS interval, but wasn't enforced from the db.

**Comment by adamkorynta** [comment]
All my client tests are now passing for this feature. I think it is good to close.
