### ISSUE TITLE
Return 404 error code for /level getOne not found

### ISSUE THREAD

**Issue by adamkorynta** [USACE/cwms-data-api#290]
Currently error code 500:

```
07-Dec-2022 22:23:01.113 SEVERE [https-jsse-nio-8443-exec-8] cwms.radar.api.LevelsController.getOne 286856900956483107: Failed to retrieve Location Level request: Failed to retrieve Location Level
	java.lang.RuntimeException: Failed to retrieve Location Level
		at cwms.radar.data.dao.LocationLevelsDaoImpl.retrieveLocationLevel(LocationLevelsDaoImpl.java:194)
		at cwms.radar.api.LevelsController.getOne(LevelsController.java:355)
		at io.javalin.apibuilder.CrudFunction$2.invoke$lambda-0(CrudHandler.kt:31)
		at io.javalin.apibuilder.CrudFunctionHandler.handle(CrudHandler.kt)
		at cwms.radar.security.CwmsAccessManager.manage(CwmsAccessManager.java:42)
		at io.javalin.http.JavalinServlet.addHandler$lambda-0(JavalinServlet.kt:96)
		at io.javalin.http.JavalinServlet$lifecycle$2$1$1.invoke(JavalinServlet.kt:43)
		at io.javalin.http.JavalinServlet$lifecycle$2$1$1.invoke(JavalinServlet.kt:43)
		at io.javalin.http.JavalinServletHandler.executeNextTask(JavalinServletHandler.kt:99)
		at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$lambda-1(JavalinServletHandler.kt:85)
		at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:995)
		at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2137)
		at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$javalin(JavalinServletHandler.kt:85)
		at io.javalin.http.JavalinServletHandler.executeNextTask$lambda-11$lambda-10(JavalinServletHandler.kt:119)
		at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616)
		at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:628)
		at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1996)
		at io.javalin.http.JavalinServletHandler.executeNextTask(JavalinServletHandler.kt:119)
		at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$lambda-1(JavalinServletHandler.kt:85)
		at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:995)
		at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2137)
		at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$javalin(JavalinServletHandler.kt:85)
		at io.javalin.http.JavalinServlet.service(JavalinServlet.kt:89)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:779)
		at cwms.radar.ApiServlet.service(ApiServlet.java:343)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:779)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:660)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
		at org.apache.catalina.authenticator.SingleSignOn.invoke(SingleSignOn.java:312)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1789)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.lang.Thread.run(Thread.java:750)
	Caused by: org.jooq.exception.DataAccessException: Error while running ConnectionCallable
		at org.jooq.impl.DefaultDSLContext.connectionResult(DefaultDSLContext.java:634)
		at org.jooq.impl.DefaultDSLContext.connection(DefaultDSLContext.java:643)
		at cwms.radar.data.dao.LocationLevelsDaoImpl.retrieveLocationLevel(LocationLevelsDaoImpl.java:185)
		... 48 more
	Caused by: java.sql.SQLException: ORA-20034: ITEM_DOES_NOT_EXIST: Location level "SWT/lvl882136.Temp.Inst.0.UnitTestLevel759893@" does not exist.
ORA-06512: at "CWMS_20.CWMS_ERR", line 59
ORA-06512: at "CWMS_20.CWMS_LEVEL", line 3167
ORA-06512: at "CWMS_20.CWMS_LEVEL", line 3416
ORA-06512: at line 1

		at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:509)
		at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:461)
		at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1104)
		at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:550)
		at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:268)
		at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:655)
		at oracle.jdbc.driver.T4CCallableStatement.doOall8(T4CCallableStatement.java:265)
		at oracle.jdbc.driver.T4CCallableStatement.doOall8(T4CCallableStatement.java:86)
		at oracle.jdbc.driver.T4CCallableStatement.executeForRows(T4CCallableStatement.java:965)
		at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1205)
		at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3666)
		at oracle.jdbc.driver.T4CCallableStatement.executeInternal(T4CCallableStatement.java:1358)
		at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3778)
		at oracle.jdbc.driver.OracleCallableStatement.execute(OracleCallableStatement.java:4251)
		at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1081)
		at sun.reflect.GeneratedMethodAccessor47.invoke(Unknown Source)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:118)
		at com.sun.proxy.$Proxy18.execute(Unknown Source)
		at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:209)
		at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:3416)
		at org.jooq.impl.AbstractRoutine.execute0(AbstractRoutine.java:521)
		at org.jooq.impl.AbstractRoutine.executeCallableStatement(AbstractRoutine.java:481)
		at org.jooq.impl.AbstractRoutine.execute(AbstractRoutine.java:344)
		at org.jooq.impl.AbstractRoutine.execute(AbstractRoutine.java:321)
		at usace.cwms.db.jooq.codegen.packages.CWMS_LEVEL_PACKAGE.call_RETRIEVE_LOCATION_LEVEL3(CWMS_LEVEL_PACKAGE.java:1502)
		at usace.cwms.db.jooq.dao.CwmsDbLevelJooq.retrieveLocationLevel_aroundBody54(CwmsDbLevelJooq.java:331)
		at usace.cwms.db.jooq.dao.CwmsDbLevelJooq$AjcClosure55.run(CwmsDbLevelJooq.java:1)
		at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:170)
		at usace.cwms.db.aspect.jooq.SQLExceptionWrapperAspect.translateToSQLException(SQLExceptionWrapperAspect.java:51)
		at usace.cwms.db.jooq.dao.CwmsDbLevelJooq.retrieveLocationLevel_aroundBody56(CwmsDbLevelJooq.java:320)
		at usace.cwms.db.jooq.dao.CwmsDbLevelJooq$AjcClosure57.run(CwmsDbLevelJooq.java:1)
		at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:170)
		at usace.cwms.db.aspect.CwmsDbTimerAspect.setupTimer(CwmsDbTimerAspect.java:65)
		at usace.cwms.db.aspect.CwmsDbTimerAspect.wrapCwmsDbJooqWithTimer(CwmsDbTimerAspect.java:25)
		at usace.cwms.db.jooq.dao.CwmsDbLevelJooq.retrieveLocationLevel(CwmsDbLevelJooq.java:320)
		at cwms.radar.data.dao.LocationLevelsDaoImpl.lambda$retrieveLocationLevel$3(LocationLevelsDaoImpl.java:187)
		at org.jooq.impl.DefaultDSLContext$4.run(DefaultDSLContext.java:646)
		at org.jooq.impl.DefaultDSLContext$4.run(DefaultDSLContext.java:643)
		at org.jooq.impl.DefaultDSLContext.connectionResult(DefaultDSLContext.java:631)
		... 50 more
	Caused by: Error : 20034, Position : 0, Sql = BEGIN "CWMS_20"."CWMS_LEVEL"."RETRIEVE_LOCATION_LEVEL3" (:1 , :2 , :3 , :4 , :5 , :6 , :7 , :8 , :9 , :10 , :11 , cast(:12  as date), :13 , :14 , :15 , :16 , :17 , :18 ) ; END;, OriginalSql = { call "CWMS_20"."CWMS_LEVEL"."RETRIEVE_LOCATION_LEVEL3" (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, cast(? as date), ?, ?, ?, ?, ?, ?) }, Error Msg = ORA-20034: ITEM_DOES_NOT_EXIST: Location level "SWT/lvl882136.Temp.Inst.0.UnitTestLevel759893@" does not exist.
ORA-06512: at "CWMS_20.CWMS_ERR", line 59
ORA-06512: at "CWMS_20.CWMS_LEVEL", line 3167
ORA-06512: at "CWMS_20.CWMS_LEVEL", line 3416
ORA-06512: at line 1

		at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:513)
		... 90 more
```

**Comment by MikeNeilson** [comment]
I was also having some issues, but I wonder if some of it is some part date parsing code, Ryan is currently fixing that and I'm going to let him do that before I really did into anything else.

**Comment by rma-rripken** [comment]
Is the issue that you'd rather it 404 than 500? Or do you think it should be finding that level?

**Comment by adamkorynta** [comment]
I'd rather it return 404 instead of 500. It was correct behavior that there was an error because I didn't store the level yet.

**Comment by adamkorynta** [comment]
Much lower priority for me than the issues tagged as blocked, just making a note here as I find things.
