### ISSUE TITLE
DataSetIllegalArgumentException: Base parameter name: "Flow" is not valid on location level getAll

### ISSUE THREAD

**Issue by adamkorynta** [USACE/cwms-data-api#400]
Retrieving location levels for a given office results in the following server-side exception

```
08-Jun-2023 22:19:12.089 WARNING [https-jsse-nio-8443-exec-8] cwms.radar.ApiServlet.lambda$init$15 error on request[3447121928785741572]: /swt-data/levels
	hec.data.DataSetIllegalArgumentException: mil.army.usace.hec.metadata.DataSetIllegalArgumentException: Base parameter name: "Flow" is not valid.
		at hec.data.Parameter.setBaseParameter(Parameter.java:402)
		at mil.army.usace.hec.metadata.Parameter.setParameter(Parameter.java:375)
		at hec.data.Parameter.setParameter(Parameter.java:385)
		at hec.data.Parameter.<init>(Parameter.java:345)
		at hec.data.Parameter.<init>(Parameter.java:333)
		at hec.data.level.JDomLocationLevelRef.<init>(JDomLocationLevelRef.java:258)
		at hec.data.level.JDomLocationLevelImpl.<init>(JDomLocationLevelImpl.java:103)
		at cwms.radar.data.dao.LocationLevelsDaoImpl.toLocationLevel(LocationLevelsDaoImpl.java:394)
		at cwms.radar.data.dao.LocationLevelsDaoImpl.lambda$getLocationLevels$3(LocationLevelsDaoImpl.java:347)
		at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
		at java.util.Iterator.forEachRemaining(Iterator.java:116)
		at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
		at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
		at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
		at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
		at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
		at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
		at cwms.radar.data.dao.LocationLevelsDaoImpl.getLocationLevels(LocationLevelsDaoImpl.java:348)
		at cwms.radar.api.LevelsController.getAll(LevelsController.java:291)
		at io.javalin.apibuilder.CrudFunction$1.invoke$lambda-0(CrudHandler.kt:30)
		at io.javalin.apibuilder.CrudFunctionHandler.handle(CrudHandler.kt)
		at cwms.radar.security.GuestAccessManager.manage(GuestAccessManager.java:21)
		at cwms.radar.security.MultipleAccessManager.manage(MultipleAccessManager.java:41)
		at io.javalin.http.JavalinServlet.addHandler$lambda-0(JavalinServlet.kt:96)
		at io.javalin.http.JavalinServlet$lifecycle$2$1$1.invoke(JavalinServlet.kt:43)
		at io.javalin.http.JavalinServlet$lifecycle$2$1$1.invoke(JavalinServlet.kt:43)
		at io.javalin.http.JavalinServletHandler.executeNextTask(JavalinServletHandler.kt:99)
		at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$lambda-1(JavalinServletHandler.kt:85)
		at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:995)
		at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2137)
		at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$javalin(JavalinServletHandler.kt:85)
		at io.javalin.http.JavalinServletHandler.executeNextTask$lambda-11$lambda-10(JavalinServletHandler.kt:119)
		at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616)
		at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:628)
		at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1996)
		at io.javalin.http.JavalinServletHandler.executeNextTask(JavalinServletHandler.kt:119)
		at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$lambda-1(JavalinServletHandler.kt:85)
		at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:995)
		at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2137)
		at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$javalin(JavalinServletHandler.kt:85)
		at io.javalin.http.JavalinServlet.service(JavalinServlet.kt:89)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:779)
		at cwms.radar.ApiServlet.service(ApiServlet.java:460)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:779)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:357)
		at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:176)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:660)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
		at org.apache.catalina.authenticator.SingleSignOn.invoke(SingleSignOn.java:261)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1789)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.lang.Thread.run(Thread.java:750)
	Caused by: mil.army.usace.hec.metadata.DataSetIllegalArgumentException: Base parameter name: "Flow" is not valid.
		at mil.army.usace.hec.metadata.Parameter.setBaseParameter(Parameter.java:530)
		at hec.data.Parameter.setBaseParameter(Parameter.java:398)
		... 70 more
```

**Comment by adamkorynta** [comment]
I believe this is related to other warning messaged in the logs:

```
08-Jun-2023 22:19:12.074 WARNING [ForkJoinPool.commonPool-worker-0] hec.data.cwmsRating.AbstractRatingSet.validate mil.army.usace.hec.metadata.DataSetIllegalArgumentException: Base parameter name: "Stage" is not valid.
08-Jun-2023 22:19:12.074 WARNING [ForkJoinPool.commonPool-worker-0] hec.data.cwmsRating.AbstractRatingSet.validate Could not initialize class mil.army.usace.hec.metadata.UnitUtil
```

**Comment by adamkorynta** [comment]
Parameter stack trace:
```
09-Jun-2023 16:43:42.102 WARNING [ForkJoinPool.commonPool-worker-1] mil.army.usace.hec.metadata.resourceservices.ParameterLookup.<clinit> Error loading Parameters.
	java.lang.NullPointerException
		at mil.army.usace.hec.metadata.resourceservices.DatabaseParameterLoader.getBufferedReader(DatabaseParameterLoader.java:94)
		at mil.army.usace.hec.metadata.resourceservices.DatabaseParameterLoader.validate(DatabaseParameterLoader.java:126)
		at mil.army.usace.hec.metadata.resourceservices.ParameterLookup.loadParameters(ParameterLookup.java:70)
		at mil.army.usace.hec.metadata.resourceservices.ParameterLookup.lookupLoadParameters(ParameterLookup.java:256)
		at mil.army.usace.hec.metadata.resourceservices.ParameterLookup.loadParameters(ParameterLookup.java:352)
		at mil.army.usace.hec.metadata.resourceservices.ParameterLookup.<clinit>(ParameterLookup.java:49)
		at hec.data.Parameter.<init>(Parameter.java:333)
		at hec.data.cwmsRating.AbstractRatingSet.validate(AbstractRatingSet.java:2459)
		at hec.data.cwmsRating.AbstractRatingSet.addRatings(AbstractRatingSet.java:320)
		at hec.data.cwmsRating.AbstractRatingSet.addRating(AbstractRatingSet.java:205)
		at hec.data.cwmsRating.AbstractRatingSet.setData(AbstractRatingSet.java:2171)
		at hec.data.cwmsRating.RatingSetFactory.ratingSet(RatingSetFactory.java:21)
		at mil.army.usace.hec.cwms.rating.io.xml.RatingXmlFactory.ratingSet(RatingXmlFactory.java:286)
		at cwms.radar.data.dao.RatingMetadataDao.getRatingSetFromXml(RatingMetadataDao.java:283)
		at cwms.radar.data.dao.RatingMetadataDao.getRatingSet(RatingMetadataDao.java:253)
		at cwms.radar.data.dao.RatingMetadataDao.retrieveRatings(RatingMetadataDao.java:211)
		at cwms.radar.data.dao.RatingMetadataDao.lambda$null$2(RatingMetadataDao.java:176)
		at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
		at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596)
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
		at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1067)
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1703)
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172)
```

and
```
09-Jun-2023 16:47:58.412 WARNING [ForkJoinPool.commonPool-worker-6] mil.army.usace.hec.metadata.resourceservices.ParameterLookup.<clinit> Error loading Parameters.
	java.lang.NullPointerException
		at rma.util.lookup.MetaInfServicesLookup.search(MetaInfServicesLookup.java:165)
		at rma.util.lookup.MetaInfServicesLookup.beforeLookup(MetaInfServicesLookup.java:139)
		at rma.util.lookup.AbstractLookup.lookupItem(AbstractLookup.java:411)
		at rma.util.lookup.AbstractLookup.lookup(AbstractLookup.java:405)
		at rma.util.lookup.Lookup.getDefault(Lookup.java:148)
		at rma.util.lookup.implspi.NamedServicesProvider.forPath(NamedServicesProvider.java:82)
		at rma.util.lookup.Lookups.forPath(Lookups.java:219)
		at mil.army.usace.hec.metadata.resourceservices.ParameterLookup.loadParameters(ParameterLookup.java:64)
		at mil.army.usace.hec.metadata.resourceservices.ParameterLookup.lookupLoadParameters(ParameterLookup.java:256)
		at mil.army.usace.hec.metadata.resourceservices.ParameterLookup.loadParameters(ParameterLookup.java:352)
		at mil.army.usace.hec.metadata.resourceservices.ParameterLookup.<clinit>(ParameterLookup.java:49)
		at hec.data.Parameter.<init>(Parameter.java:333)
		at hec.data.cwmsRating.AbstractRatingSet.validate(AbstractRatingSet.java:2459)
		at hec.data.cwmsRating.AbstractRatingSet.addRatings(AbstractRatingSet.java:320)
		at hec.data.cwmsRating.AbstractRatingSet.addRating(AbstractRatingSet.java:205)
		at hec.data.cwmsRating.AbstractRatingSet.setData(AbstractRatingSet.java:2171)
		at hec.data.cwmsRating.RatingSetFactory.ratingSet(RatingSetFactory.java:21)
		at mil.army.usace.hec.cwms.rating.io.xml.RatingXmlFactory.ratingSet(RatingXmlFactory.java:286)
		at cwms.radar.data.dao.RatingMetadataDao.getRatingSetFromXml(RatingMetadataDao.java:283)
		at cwms.radar.data.dao.RatingMetadataDao.getRatingSet(RatingMetadataDao.java:253)
		at cwms.radar.data.dao.RatingMetadataDao.retrieveRatings(RatingMetadataDao.java:211)
		at cwms.radar.data.dao.RatingMetadataDao.lambda$null$2(RatingMetadataDao.java:176)
		at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
		at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596)
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
		at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1067)
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1703)
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172)
```
