### ISSUE TITLE
Unable to update assigned locations/time series in CWMS owned groups

### ISSUE THREAD

**Issue by adamkorynta** [USACE/cwms-data-api#421]
Due to the new way of getting the session office ids, editing assigned locations or assigned time series for groups like "Default", "Agency Aliases", etc throws an error saying the user doesn't have permissions for the office "CWMS".  

```
13-Jul-2023 21:52:59.757 WARNING [https-jsse-nio-8443-exec-496] cwms.cda.ApiServlet.lambda$init$15 error on request[279266227818703770]: /swt-data/timeseries/group/Default
	org.jooq.exception.DataAccessException: Error while running ConnectionCallable
		at org.jooq.impl.DefaultDSLContext.connectionResult(DefaultDSLContext.java:634)
		at org.jooq.impl.DefaultDSLContext.connection(DefaultDSLContext.java:643)
		at cwms.cda.data.dao.TimeSeriesGroupDao.unassignAllTs(TimeSeriesGroupDao.java:249)
		at cwms.cda.api.TimeSeriesGroupController.update(TimeSeriesGroupController.java:263)
		at io.javalin.apibuilder.CrudFunction$4.invoke$lambda-0(CrudHandler.kt:33)
		at io.javalin.apibuilder.CrudFunctionHandler.handle(CrudHandler.kt)
		at cwms.cda.security.KeyAccessManager.manage(KeyAccessManager.java:36)
		at cwms.cda.security.MultipleAccessManager.manage(MultipleAccessManager.java:41)
		at io.javalin.http.JavalinServlet.addHandler$lambda-0(JavalinServlet.kt:96)
		at io.javalin.http.JavalinServlet$lifecycle$2$1$1.invoke(JavalinServlet.kt:43)
		at io.javalin.http.JavalinServlet$lifecycle$2$1$1.invoke(JavalinServlet.kt:43)
		at io.javalin.http.JavalinServletHandler.executeNextTask(JavalinServletHandler.kt:99)
		at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$lambda-1(JavalinServletHandler.kt:85)
		at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:995)
		at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2137)
		at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$javalin(JavalinServletHandler.kt:85)
		at io.javalin.http.JavalinServletHandler.executeNextTask$lambda-11$lambda-10(JavalinServletHandler.kt:119)
		at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616)
		at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:628)
		at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1996)
		at io.javalin.http.JavalinServletHandler.executeNextTask(JavalinServletHandler.kt:119)
		at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$lambda-1(JavalinServletHandler.kt:85)
		at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:995)
		at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2137)
		at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$javalin(JavalinServletHandler.kt:85)
		at io.javalin.http.JavalinServlet.service(JavalinServlet.kt:89)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:779)
		at cwms.cda.ApiServlet.service(ApiServlet.java:510)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:779)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:357)
		at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:176)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:660)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
		at org.apache.catalina.authenticator.SingleSignOn.invoke(SingleSignOn.java:261)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1789)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.lang.Thread.run(Thread.java:750)
	Caused by: org.jooq.exception.DataAccessException: SQL [{ call "CWMS_20"."CWMS_ENV"."SET_SESSION_OFFICE_ID" (?) }]; ORA-20998: ERROR: Unable to set SESSION_OFFICE_ID to: CWMS because user: M5HECTEST does not have any assigned privileges for that office.
ORA-06512: at "CWMS_20.CWMS_ERR", line 59
ORA-06512: at "CWMS_20.CWMS_ENV", line 73
ORA-06512: at line 1

		at org.jooq_3.11.2.ORACLE11G.debug(Unknown Source)
		at org.jooq.impl.Tools.translate(Tools.java:2380)
		at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:811)
		at org.jooq.impl.AbstractRoutine.executeCallableStatement(AbstractRoutine.java:510)
		at org.jooq.impl.AbstractRoutine.execute(AbstractRoutine.java:344)
		at org.jooq.impl.AbstractRoutine.execute(AbstractRoutine.java:321)
		at usace.cwms.db.jooq.codegen.packages.CWMS_ENV_PACKAGE.call_SET_SESSION_OFFICE_ID(CWMS_ENV_PACKAGE.java:57)
		at cwms.cda.data.dao.JooqDao.getDslContext(JooqDao.java:105)
		at cwms.cda.data.dao.TimeSeriesGroupDao.lambda$unassignAllTs$6(TimeSeriesGroupDao.java:251)
		at org.jooq.impl.DefaultDSLContext$4.run(DefaultDSLContext.java:646)
		at org.jooq.impl.DefaultDSLContext$4.run(DefaultDSLContext.java:643)
		at org.jooq.impl.DefaultDSLContext.connectionResult(DefaultDSLContext.java:631)
		... 55 more
	Caused by: java.sql.SQLException: ORA-20998: ERROR: Unable to set SESSION_OFFICE_ID to: CWMS because user: M5HECTEST does not have any assigned privileges for that office.
ORA-06512: at "CWMS_20.CWMS_ERR", line 59
ORA-06512: at "CWMS_20.CWMS_ENV", line 73
ORA-06512: at line 1

		at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:509)
		at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:461)
		at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1104)
		at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:550)
		at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:268)
		at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:655)
		at oracle.jdbc.driver.T4CCallableStatement.doOall8(T4CCallableStatement.java:265)
		at oracle.jdbc.driver.T4CCallableStatement.doOall8(T4CCallableStatement.java:86)
		at oracle.jdbc.driver.T4CCallableStatement.executeForRows(T4CCallableStatement.java:965)
		at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1205)
		at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3666)
		at oracle.jdbc.driver.T4CCallableStatement.executeInternal(T4CCallableStatement.java:1358)
		at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3778)
		at oracle.jdbc.driver.OracleCallableStatement.execute(OracleCallableStatement.java:4251)
		at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1081)
		at sun.reflect.GeneratedMethodAccessor47.invoke(Unknown Source)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:118)
		at com.sun.proxy.$Proxy14.execute(Unknown Source)
		at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:209)
		at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:3416)
		at org.jooq.impl.AbstractRoutine.execute0(AbstractRoutine.java:521)
		at org.jooq.impl.AbstractRoutine.executeCallableStatement(AbstractRoutine.java:481)
		... 63 more
	Caused by: Error : 20998, Position : 0, Sql = BEGIN "CWMS_20"."CWMS_ENV"."SET_SESSION_OFFICE_ID" (:1 ) ; END;, OriginalSql = { call "CWMS_20"."CWMS_ENV"."SET_SESSION_OFFICE_ID" (?) }, Error Msg = ORA-20998: ERROR: Unable to set SESSION_OFFICE_ID to: CWMS because user: M5HECTEST does not have any assigned privileges for that office.
ORA-06512: at "CWMS_20.CWMS_ERR", line 59
ORA-06512: at "CWMS_20.CWMS_ENV", line 73
ORA-06512: at line 1

		at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:513)
		... 86 more
```

**Comment by MikeNeilson** [comment]
Hmm, that's technically correct. Most users should've have permissions to writing anything under CWMS.
Though the plan is to allow automated processes permissions on those. Like an LRGS/RoutingScheduler writing the data.

But I'm going to have to review how that's default groups are setup first before I decided if this is "works as intended" or not.

Thought @perrymanmd might have some more insight sooner.

**Comment by zack-rma** [comment]
This issue has been resolved. It has test coverage that was added for another ticket addressing the same issue: https://github.com/USACE/cwms-data-api/pull/900
