### ISSUE TITLE
Bad unit in timeseries post returns 500 instead of reasoanble message.

### ISSUE THREAD

**Issue by MikeNeilson** [USACE/cwms-data-api#630]
stack trace:
```
        org.jooq.exception.DataAccessException: Error while running ConnectionCallable
                at org.jooq.impl.DefaultDSLContext.connectionResult(DefaultDSLContext.java:664)
                at org.jooq.impl.DefaultDSLContext.connection(DefaultDSLContext.java:696)
                at cwms.cda.data.dao.JooqDao.connection(JooqDao.java:435)
                at cwms.cda.data.dao.TimeSeriesDaoImpl.create(TimeSeriesDaoImpl.java:903)
                at cwms.cda.api.TimeSeriesController.create(TimeSeriesController.java:213)
                at io.javalin.apibuilder.CrudFunction$3.invoke$lambda-0(CrudHandler.kt:32)
                at io.javalin.apibuilder.CrudFunctionHandler.handle(CrudHandler.kt)
                at cwms.cda.security.CwmsAccessManager.manage(CwmsAccessManager.java:33)
                at cwms.cda.security.MultipleAccessManager.manage(MultipleAccessManager.java:41)
                at io.javalin.http.JavalinServlet.addHandler$lambda-0(JavalinServlet.kt:96)
                at io.javalin.http.JavalinServlet$lifecycle$2$1$1.invoke(JavalinServlet.kt:43)
                at io.javalin.http.JavalinServlet$lifecycle$2$1$1.invoke(JavalinServlet.kt:43)
                at io.javalin.http.JavalinServletHandler.executeNextTask(JavalinServletHandler.kt:99)
                at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$lambda-1(JavalinServletHandler.kt:85)
                at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:995)
                at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2137)
                at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$javalin(JavalinServletHandler.kt:85)
                at io.javalin.http.JavalinServletHandler.executeNextTask$lambda-11$lambda-10(JavalinServletHandler.kt:119)
                at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616)
                at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:628)
                at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1996)
                at io.javalin.http.JavalinServletHandler.executeNextTask(JavalinServletHandler.kt:119)
                at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$lambda-1(JavalinServletHandler.kt:85)
                at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:995)
                at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2137)
                at io.javalin.http.JavalinServletHandler.queueNextTaskOrFinish$javalin(JavalinServletHandler.kt:85)
                at io.javalin.http.JavalinServlet.service(JavalinServlet.kt:89)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:583)
                at cwms.cda.ApiServlet.service(ApiServlet.java:622)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:583)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:212)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
                at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:181)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
                at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:129)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:181)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
                at org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:333)
                at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:155)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:181)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
                at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168)
                at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
                at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:598)
                at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
                at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:679)
                at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:679)
                at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
                at org.apache.catalina.authenticator.SingleSignOn.invoke(SingleSignOn.java:289)
                at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
                at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:765)
                at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
                at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:617)
                at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
                at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:934)
                at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1698)
                at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
                at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
                at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
                at java.lang.Thread.run(Thread.java:750)
        Caused by: java.sql.SQLException: ORA-20998: ERROR: ORA-06512: at "CWMS_20.CWMS_UTIL", line 2611
ORA-06512: at "CWMS_20.CWMS_UTIL", line 2595
ORA-06512: at "CWMS_20.CWMS_UTIL", line 2587
ORA-06512: at "CWMS_20.CWMS_TS", line 5579
ORA-06512: at "CWMS_20.CWMS_ERR", line 80
ORA-06512: at "CWMS_20.CWMS_TS", line 6677
ORA-20102: The unit: m is not a recognized CWMS Database unit for the Flow Parameter_ID.
ORA-06512: at "CWMS_20.CWMS_UTIL", line 2611
ORA-01403: no data found
ORA-06512: at "CWMS_20.CWMS_UTIL", line 2595
ORA-01403: no data found
ORA-06512: at "CWMS_20.CWMS_UTIL", line 2587
ORA-06512: at "CWMS_20.CWMS_TS", line 5579
ORA-06512: at "CWMS_20.CWMS_TS", line 5038
ORA-06512: at "CWMS_20.CWMS_TS", line 9213
ORA-06512: at line 1

                at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:509)
                at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:461)
                at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1104)
                at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:553)
                at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:269)
                at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:655)
                at oracle.jdbc.driver.T4CCallableStatement.doOall8(T4CCallableStatement.java:265)
                at oracle.jdbc.driver.T4CCallableStatement.doOall8(T4CCallableStatement.java:86)
                at oracle.jdbc.driver.T4CCallableStatement.executeForRows(T4CCallableStatement.java:965)
                at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1205)
                at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3666)
                at oracle.jdbc.driver.T4CCallableStatement.executeInternal(T4CCallableStatement.java:1358)
                at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3778)
                at oracle.jdbc.driver.OracleCallableStatement.execute(OracleCallableStatement.java:4251)
                at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1081)
                at sun.reflect.GeneratedMethodAccessor53.invoke(Unknown Source)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at org.apache.tomcat.jdbc.pool.interceptor.AbstractQueryReport$StatementProxy.invoke(AbstractQueryReport.java:214)
                at com.sun.proxy.$Proxy48.execute(Unknown Source)
                at sun.reflect.GeneratedMethodAccessor53.invoke(Unknown Source)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at org.apache.tomcat.jdbc.pool.interceptor.AbstractQueryReport$StatementProxy.invoke(AbstractQueryReport.java:214)
                at com.sun.proxy.$Proxy48.execute(Unknown Source)
                at sun.reflect.GeneratedMethodAccessor53.invoke(Unknown Source)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:118)
                at com.sun.proxy.$Proxy48.execute(Unknown Source)
                at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:219)
                at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:4695)
                at org.jooq.impl.AbstractRoutine.execute0(AbstractRoutine.java:622)
                at org.jooq.impl.AbstractRoutine.executeCallableStatement(AbstractRoutine.java:582)
                at org.jooq.impl.AbstractRoutine.execute(AbstractRoutine.java:405)
                at org.jooq.impl.Tools.attach(Tools.java:1610)
                at org.jooq.impl.AbstractRoutine.execute(AbstractRoutine.java:374)
                at usace.cwms.db.jooq.codegen.packages.CWMS_TS_PACKAGE.call_ZSTORE_TS(CWMS_TS_PACKAGE.java:8095)
                at usace.cwms.db.jooq.dao.CwmsDbTsJooq.store_aroundBody12(CwmsDbTsJooq.java:248)
                at usace.cwms.db.jooq.dao.CwmsDbTsJooq$AjcClosure13.run(CwmsDbTsJooq.java:1)
                at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:183)
                at usace.cwms.db.aspect.CwmsDbTimerAspect.setupTimer(CwmsDbTimerAspect.java:65)
                at usace.cwms.db.aspect.CwmsDbTimerAspect.wrapCwmsDbJooqWithTimer(CwmsDbTimerAspect.java:25)
                at usace.cwms.db.jooq.dao.CwmsDbTsJooq.store_aroundBody14(CwmsDbTsJooq.java:216)
                at usace.cwms.db.jooq.dao.CwmsDbTsJooq$AjcClosure15.run(CwmsDbTsJooq.java:1)
                at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:183)
                at usace.cwms.db.aspect.jooq.SQLExceptionWrapperAspect.translateToSQLException(SQLExceptionWrapperAspect.java:51)
                at usace.cwms.db.jooq.dao.CwmsDbTsJooq.store(CwmsDbTsJooq.java:216)
                at cwms.cda.data.dao.TimeSeriesDaoImpl.store(TimeSeriesDaoImpl.java:978)
                at cwms.cda.data.dao.TimeSeriesDaoImpl.lambda$create$13(TimeSeriesDaoImpl.java:915)
                at org.jooq.impl.DefaultDSLContext.lambda$connection$12(DefaultDSLContext.java:697)
                at org.jooq.impl.DefaultDSLContext.connectionResult(DefaultDSLContext.java:658)
                ... 61 more
        Caused by: Error : 20998, Position : 0, Sql = BEGIN "CWMS_20"."CWMS_TS"."ZSTORE_TS" (:1 , :2 , :3 , :4 , :5 , cast(:6  as date), :7 , :8 ) ; END;, OriginalSql = { call "CWMS_20"."CWMS_TS"."ZSTORE_TS" (?, ?, ?, ?, ?, cast(? as date), ?, ?) }, Error Msg = ORA-20998: ERROR: ORA-06512: at "CWMS_20.CWMS_UTIL", line 2611
ORA-06512: at "CWMS_20.CWMS_UTIL", line 2595
ORA-06512: at "CWMS_20.CWMS_UTIL", line 2587
ORA-06512: at "CWMS_20.CWMS_TS", line 5579
ORA-06512: at "CWMS_20.CWMS_ERR", line 80
ORA-06512: at "CWMS_20.CWMS_TS", line 6677
ORA-20102: The unit: m is not a recognized CWMS Database unit for the Flow Parameter_ID.
ORA-06512: at "CWMS_20.CWMS_UTIL", line 2611
ORA-01403: no data found
ORA-06512: at "CWMS_20.CWMS_UTIL", line 2595
ORA-01403: no data found
ORA-06512: at "CWMS_20.CWMS_UTIL", line 2587
ORA-06512: at "CWMS_20.CWMS_TS", line 5579
ORA-06512: at "CWMS_20.CWMS_TS", line 5038
ORA-06512: at "CWMS_20.CWMS_TS", line 9213
ORA-06512: at line 1

                at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:513)
                ... 112 more

```

**Comment by rma-rripken** [comment]
Does a 400 and a json response like this make more sense?

{
    "message": "Bad Request.",
    "incidentIdentifier": "-1352948699897044010",
    "details": {
        "message": "ORA-20102: The unit: m is not a recognized CWMS Database unit for the Temp Parameter_ID."
    }
}

**Comment by MikeNeilson** [comment]
400 yes, but we don't want to embed the oracle message in there. Granted everybody and their uncle already know we're using oracle because, well, public repository, but we shouldn't make it that obvious at runtime.

Everything after the `ORA-20102:` is reasonable but make sure it runs through the sanitizer, otherwise we have a XSS issue.
