### ISSUE TITLE
timeseries/group/{group-id} API returns "Formatting error"

### ISSUE THREAD

**Issue by adamkorynta** [USACE/cwms-data-api#93]
Example query: localhost:11524/timeseries/group/Default?office=CWMS&category-id=Default

Returns:
```
{
    "message": "Formatting error",
    "incidentIdentifier": "9204659466428587181",
    "details": {}
}
```

Server-side stack trace:
```
Nov 05, 2021 4:35:47 PM mil.army.usace.hec.RadarAPI lambda$new$6
SEVERE: 9204659466428587181: Formatting errorfor request: http://localhost:11524/timeseries/group/Default?office=CWMS&category-id=Default
cwms.radar.formatters.FormattingException: No Format for this content-type and data-type : (application/json, cwms.radar.data.dto.TimeSeriesGroup)
	at cwms.radar.formatters.Formats.getFormatted(Formats.java:113)
	at cwms.radar.formatters.Formats.format(Formats.java:158)
	at cwms.radar.api.TimeSeriesGroupController.getOne(TimeSeriesGroupController.java:137)
	at io.javalin.apibuilder.CrudFunction$2.invoke$lambda-0(CrudHandler.kt:31)
	at io.javalin.apibuilder.CrudFunctionHandler.handle(CrudHandler.kt)
	at io.javalin.core.security.SecurityUtil.noopAccessManager(SecurityUtil.kt:20)
	at io.javalin.http.JavalinServlet.addHandler$lambda-5(JavalinServlet.kt:113)
	at io.javalin.http.JavalinServlet$service$tryBeforeAndEndpointHandlers$1.invoke(JavalinServlet.kt:44)
	at io.javalin.http.JavalinServlet$service$tryBeforeAndEndpointHandlers$1.invoke(JavalinServlet.kt:39)
	at io.javalin.http.JavalinServlet.service$tryWithExceptionMapper(JavalinServlet.kt:129)
	at io.javalin.http.JavalinServlet.service$tryBeforeAndEndpointHandlers(JavalinServlet.kt:39)
	at io.javalin.http.JavalinServlet.service(JavalinServlet.kt:87)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at io.javalin.jetty.JavalinJettyServlet.service(JavalinJettyServlet.kt:58)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at io.javalin.jetty.JettyServer$start$wsAndHttpHandler$1.doHandle(JettyServer.kt:52)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:179)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by rripken** [comment]
I'm not able to duplicate this it might have been fixed by other changes.

**Comment by MikeNeilson** [comment]
That's probably true. it wouldn't surprise me if this was fixed when we reorded the endpoints.
